import type { EffectFamily } from '../types';

export const MOVE_OVERRIDES: Record<string, { family: EffectFamily }> = {
  flamethrower:    { family: 'beam' },
  fireblast:       { family: 'beam' },
  overheat:        { family: 'beam' },
  heatwave:        { family: 'cloud' },
  eruption:        { family: 'burst' },
  surf:            { family: 'impact' },
  hydrocannon:     { family: 'beam' },
  hydropump:       { family: 'beam' },
  scald:           { family: 'cloud' },
  thunder:         { family: 'beam' },
  thunderbolt:     { family: 'beam' },
  discharge:       { family: 'pulse' },
  solarbeam:       { family: 'beam' },
  leafblade:       { family: 'slash' },
  leafstorm:       { family: 'cloud' },
  blizzard:        { family: 'frost' },
  icebeam:         { family: 'beam' },
  closecombat:     { family: 'impact' },
  crosschop:       { family: 'slash' },
  psychic:         { family: 'pulse' },
  futuresight:     { family: 'pulse' },
  shadowball:      { family: 'projectile' },
  shadowclaw:      { family: 'slash' },
  dracometeor:     { family: 'beam' },
  dragonpulse:     { family: 'beam' },
  darkpulse:       { family: 'beam' },
  nightdaze:       { family: 'pulse' },
  moonblast:       { family: 'projectile' },
  playrough:       { family: 'impact' },
  flashcannon:     { family: 'beam' },
  ironhead:        { family: 'impact' },
  rockslide:       { family: 'impact' },
  stoneedge:       { family: 'projectile' },
  earthquake:      { family: 'impact' },
  earthpower:      { family: 'beam' },
  mudslap:         { family: 'cloud' },
  hurricane:       { family: 'cloud' },
  bravebird:       { family: 'impact' },
  airslash:        { family: 'slash' },
  bugbuzz:         { family: 'swarm' },
  sludgebomb:      { family: 'projectile' },
  sludgewave:      { family: 'cloud' },
  hyperbeam:       { family: 'beam' },
  gunkshot:        { family: 'projectile' },
};
