// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
import type { BerryData } from './schemas/index.ts';

export const BERRIES: BerryData[] = [
  {
    "id": 1,
    "name": "cheri",
    "firmness": "soft",
    "growthTime": 3,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "fire",
    "size": 20,
    "smoothness": 25,
    "soilDryness": 15,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/cheri-berry.png"
  },
  {
    "id": 2,
    "name": "chesto",
    "firmness": "super-hard",
    "growthTime": 3,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "water",
    "size": 80,
    "smoothness": 25,
    "soilDryness": 15,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/chesto-berry.png"
  },
  {
    "id": 3,
    "name": "pecha",
    "firmness": "very-soft",
    "growthTime": 3,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "electric",
    "size": 40,
    "smoothness": 25,
    "soilDryness": 15,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/pecha-berry.png"
  },
  {
    "id": 4,
    "name": "rawst",
    "firmness": "hard",
    "growthTime": 3,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "grass",
    "size": 32,
    "smoothness": 25,
    "soilDryness": 15,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/rawst-berry.png"
  },
  {
    "id": 5,
    "name": "aspear",
    "firmness": "super-hard",
    "growthTime": 3,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ice",
    "size": 50,
    "smoothness": 25,
    "soilDryness": 15,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/aspear-berry.png"
  },
  {
    "id": 6,
    "name": "leppa",
    "firmness": "very-hard",
    "growthTime": 4,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "fighting",
    "size": 28,
    "smoothness": 20,
    "soilDryness": 15,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 10,
      "bitter": 10,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/leppa-berry.png"
  },
  {
    "id": 7,
    "name": "oran",
    "firmness": "super-hard",
    "growthTime": 4,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "poison",
    "size": 35,
    "smoothness": 20,
    "soilDryness": 15,
    "flavors": {
      "spicy": 10,
      "dry": 10,
      "sweet": 0,
      "bitter": 10,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/oran-berry.png"
  },
  {
    "id": 8,
    "name": "persim",
    "firmness": "hard",
    "growthTime": 4,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ground",
    "size": 47,
    "smoothness": 20,
    "soilDryness": 15,
    "flavors": {
      "spicy": 10,
      "dry": 10,
      "sweet": 10,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/persim-berry.png"
  },
  {
    "id": 9,
    "name": "lum",
    "firmness": "super-hard",
    "growthTime": 12,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "flying",
    "size": 34,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 10,
      "dry": 10,
      "sweet": 10,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/lum-berry.png"
  },
  {
    "id": 10,
    "name": "sitrus",
    "firmness": "very-hard",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "psychic",
    "size": 95,
    "smoothness": 20,
    "soilDryness": 7,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 10,
      "bitter": 10,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/sitrus-berry.png"
  },
  {
    "id": 11,
    "name": "figy",
    "firmness": "soft",
    "growthTime": 5,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "bug",
    "size": 100,
    "smoothness": 25,
    "soilDryness": 10,
    "flavors": {
      "spicy": 15,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/figy-berry.png"
  },
  {
    "id": 12,
    "name": "wiki",
    "firmness": "hard",
    "growthTime": 5,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "rock",
    "size": 115,
    "smoothness": 25,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 15,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/wiki-berry.png"
  },
  {
    "id": 13,
    "name": "mago",
    "firmness": "hard",
    "growthTime": 5,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ghost",
    "size": 126,
    "smoothness": 25,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 15,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/mago-berry.png"
  },
  {
    "id": 14,
    "name": "aguav",
    "firmness": "super-hard",
    "growthTime": 5,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "dragon",
    "size": 64,
    "smoothness": 25,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 15,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/aguav-berry.png"
  },
  {
    "id": 15,
    "name": "iapapa",
    "firmness": "soft",
    "growthTime": 5,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "dark",
    "size": 223,
    "smoothness": 25,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 15
    },
    "spritePath": "/assets/items/berries/iapapa-berry.png"
  },
  {
    "id": 16,
    "name": "razz",
    "firmness": "very-hard",
    "growthTime": 2,
    "maxHarvest": 10,
    "naturalGiftPower": 60,
    "naturalGiftType": "steel",
    "size": 120,
    "smoothness": 20,
    "soilDryness": 35,
    "flavors": {
      "spicy": 10,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/razz-berry.png"
  },
  {
    "id": 17,
    "name": "bluk",
    "firmness": "soft",
    "growthTime": 2,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "fire",
    "size": 108,
    "smoothness": 20,
    "soilDryness": 35,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/bluk-berry.png"
  },
  {
    "id": 18,
    "name": "nanab",
    "firmness": "very-hard",
    "growthTime": 2,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "water",
    "size": 77,
    "smoothness": 20,
    "soilDryness": 35,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 10,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/nanab-berry.png"
  },
  {
    "id": 19,
    "name": "wepear",
    "firmness": "super-hard",
    "growthTime": 2,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "electric",
    "size": 74,
    "smoothness": 20,
    "soilDryness": 35,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 10,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/wepear-berry.png"
  },
  {
    "id": 20,
    "name": "pinap",
    "firmness": "hard",
    "growthTime": 2,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "grass",
    "size": 80,
    "smoothness": 20,
    "soilDryness": 35,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/pinap-berry.png"
  },
  {
    "id": 21,
    "name": "pomeg",
    "firmness": "very-hard",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "ice",
    "size": 135,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 10,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/pomeg-berry.png"
  },
  {
    "id": 22,
    "name": "kelpsy",
    "firmness": "hard",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "fighting",
    "size": 150,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 0,
      "bitter": 10,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/kelpsy-berry.png"
  },
  {
    "id": 23,
    "name": "qualot",
    "firmness": "hard",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "poison",
    "size": 110,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 10,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/qualot-berry.png"
  },
  {
    "id": 24,
    "name": "hondew",
    "firmness": "hard",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "ground",
    "size": 162,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 10,
      "dry": 10,
      "sweet": 0,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/hondew-berry.png"
  },
  {
    "id": 25,
    "name": "grepa",
    "firmness": "soft",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "flying",
    "size": 149,
    "smoothness": 20,
    "soilDryness": 8,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 10,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/grepa-berry.png"
  },
  {
    "id": 26,
    "name": "tamato",
    "firmness": "soft",
    "growthTime": 8,
    "maxHarvest": 5,
    "naturalGiftPower": 70,
    "naturalGiftType": "psychic",
    "size": 200,
    "smoothness": 30,
    "soilDryness": 8,
    "flavors": {
      "spicy": 20,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/tamato-berry.png"
  },
  {
    "id": 27,
    "name": "cornn",
    "firmness": "hard",
    "growthTime": 6,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "bug",
    "size": 75,
    "smoothness": 30,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 20,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/cornn-berry.png"
  },
  {
    "id": 28,
    "name": "magost",
    "firmness": "hard",
    "growthTime": 6,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "rock",
    "size": 140,
    "smoothness": 30,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 20,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/magost-berry.png"
  },
  {
    "id": 29,
    "name": "rabuta",
    "firmness": "soft",
    "growthTime": 6,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "ghost",
    "size": 226,
    "smoothness": 30,
    "soilDryness": 10,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 20,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/rabuta-berry.png"
  },
  {
    "id": 30,
    "name": "nomel",
    "firmness": "super-hard",
    "growthTime": 6,
    "maxHarvest": 10,
    "naturalGiftPower": 70,
    "naturalGiftType": "dragon",
    "size": 285,
    "smoothness": 30,
    "soilDryness": 10,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 20
    },
    "spritePath": "/assets/items/berries/nomel-berry.png"
  },
  {
    "id": 31,
    "name": "spelon",
    "firmness": "soft",
    "growthTime": 15,
    "maxHarvest": 15,
    "naturalGiftPower": 70,
    "naturalGiftType": "dark",
    "size": 133,
    "smoothness": 35,
    "soilDryness": 8,
    "flavors": {
      "spicy": 30,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/spelon-berry.png"
  },
  {
    "id": 32,
    "name": "pamtre",
    "firmness": "very-soft",
    "growthTime": 15,
    "maxHarvest": 15,
    "naturalGiftPower": 70,
    "naturalGiftType": "steel",
    "size": 244,
    "smoothness": 35,
    "soilDryness": 8,
    "flavors": {
      "spicy": 0,
      "dry": 30,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/pamtre-berry.png"
  },
  {
    "id": 33,
    "name": "watmel",
    "firmness": "soft",
    "growthTime": 15,
    "maxHarvest": 15,
    "naturalGiftPower": 80,
    "naturalGiftType": "fire",
    "size": 250,
    "smoothness": 35,
    "soilDryness": 8,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 30,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/watmel-berry.png"
  },
  {
    "id": 34,
    "name": "durin",
    "firmness": "hard",
    "growthTime": 15,
    "maxHarvest": 15,
    "naturalGiftPower": 80,
    "naturalGiftType": "water",
    "size": 280,
    "smoothness": 35,
    "soilDryness": 8,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 30,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/durin-berry.png"
  },
  {
    "id": 35,
    "name": "belue",
    "firmness": "very-soft",
    "growthTime": 15,
    "maxHarvest": 15,
    "naturalGiftPower": 80,
    "naturalGiftType": "electric",
    "size": 300,
    "smoothness": 35,
    "soilDryness": 8,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 30
    },
    "spritePath": "/assets/items/berries/belue-berry.png"
  },
  {
    "id": 36,
    "name": "occa",
    "firmness": "super-hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "fire",
    "size": 90,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 15,
      "dry": 0,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/occa-berry.png"
  },
  {
    "id": 37,
    "name": "passho",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "water",
    "size": 33,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 15,
      "sweet": 0,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/passho-berry.png"
  },
  {
    "id": 38,
    "name": "wacan",
    "firmness": "very-soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "electric",
    "size": 250,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 15,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/wacan-berry.png"
  },
  {
    "id": 39,
    "name": "rindo",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "grass",
    "size": 156,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 15,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/rindo-berry.png"
  },
  {
    "id": 40,
    "name": "yache",
    "firmness": "very-hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ice",
    "size": 135,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 15
    },
    "spritePath": "/assets/items/berries/yache-berry.png"
  },
  {
    "id": 41,
    "name": "chople",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "fighting",
    "size": 77,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 15,
      "dry": 0,
      "sweet": 0,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/chople-berry.png"
  },
  {
    "id": 42,
    "name": "kebia",
    "firmness": "hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "poison",
    "size": 90,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 15,
      "sweet": 0,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/kebia-berry.png"
  },
  {
    "id": 43,
    "name": "shuca",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ground",
    "size": 42,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 15,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/shuca-berry.png"
  },
  {
    "id": 44,
    "name": "coba",
    "firmness": "very-hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "flying",
    "size": 278,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 0,
      "bitter": 15,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/coba-berry.png"
  },
  {
    "id": 45,
    "name": "payapa",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "psychic",
    "size": 252,
    "smoothness": 30,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 10,
      "bitter": 0,
      "sour": 15
    },
    "spritePath": "/assets/items/berries/payapa-berry.png"
  },
  {
    "id": 46,
    "name": "tanga",
    "firmness": "very-soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "bug",
    "size": 42,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 20,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/tanga-berry.png"
  },
  {
    "id": 47,
    "name": "charti",
    "firmness": "very-soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "rock",
    "size": 28,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 10,
      "dry": 20,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/charti-berry.png"
  },
  {
    "id": 48,
    "name": "kasib",
    "firmness": "hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "ghost",
    "size": 144,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 10,
      "sweet": 20,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/kasib-berry.png"
  },
  {
    "id": 49,
    "name": "haban",
    "firmness": "soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "dragon",
    "size": 23,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 10,
      "bitter": 20,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/haban-berry.png"
  },
  {
    "id": 50,
    "name": "colbur",
    "firmness": "super-hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "dark",
    "size": 39,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 10,
      "sour": 20
    },
    "spritePath": "/assets/items/berries/colbur-berry.png"
  },
  {
    "id": 51,
    "name": "babiri",
    "firmness": "super-hard",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "steel",
    "size": 265,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 25,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/babiri-berry.png"
  },
  {
    "id": 52,
    "name": "chilan",
    "firmness": "very-soft",
    "growthTime": 18,
    "maxHarvest": 5,
    "naturalGiftPower": 60,
    "naturalGiftType": "normal",
    "size": 34,
    "smoothness": 35,
    "soilDryness": 6,
    "flavors": {
      "spicy": 0,
      "dry": 25,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/chilan-berry.png"
  },
  {
    "id": 53,
    "name": "liechi",
    "firmness": "very-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "grass",
    "size": 111,
    "smoothness": 40,
    "soilDryness": 4,
    "flavors": {
      "spicy": 30,
      "dry": 10,
      "sweet": 30,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/liechi-berry.png"
  },
  {
    "id": 54,
    "name": "ganlon",
    "firmness": "very-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "ice",
    "size": 33,
    "smoothness": 40,
    "soilDryness": 4,
    "flavors": {
      "spicy": 0,
      "dry": 30,
      "sweet": 10,
      "bitter": 30,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/ganlon-berry.png"
  },
  {
    "id": 55,
    "name": "salac",
    "firmness": "very-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "fighting",
    "size": 95,
    "smoothness": 40,
    "soilDryness": 4,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 30,
      "bitter": 10,
      "sour": 30
    },
    "spritePath": "/assets/items/berries/salac-berry.png"
  },
  {
    "id": 56,
    "name": "petaya",
    "firmness": "very-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "poison",
    "size": 237,
    "smoothness": 40,
    "soilDryness": 4,
    "flavors": {
      "spicy": 30,
      "dry": 0,
      "sweet": 0,
      "bitter": 30,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/petaya-berry.png"
  },
  {
    "id": 57,
    "name": "apicot",
    "firmness": "hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "ground",
    "size": 75,
    "smoothness": 40,
    "soilDryness": 4,
    "flavors": {
      "spicy": 10,
      "dry": 30,
      "sweet": 0,
      "bitter": 0,
      "sour": 30
    },
    "spritePath": "/assets/items/berries/apicot-berry.png"
  },
  {
    "id": 58,
    "name": "lansat",
    "firmness": "soft",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "flying",
    "size": 97,
    "smoothness": 50,
    "soilDryness": 4,
    "flavors": {
      "spicy": 30,
      "dry": 10,
      "sweet": 30,
      "bitter": 10,
      "sour": 30
    },
    "spritePath": "/assets/items/berries/lansat-berry.png"
  },
  {
    "id": 59,
    "name": "starf",
    "firmness": "super-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "psychic",
    "size": 153,
    "smoothness": 50,
    "soilDryness": 4,
    "flavors": {
      "spicy": 30,
      "dry": 10,
      "sweet": 30,
      "bitter": 10,
      "sour": 30
    },
    "spritePath": "/assets/items/berries/starf-berry.png"
  },
  {
    "id": 60,
    "name": "enigma",
    "firmness": "hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "bug",
    "size": 155,
    "smoothness": 60,
    "soilDryness": 7,
    "flavors": {
      "spicy": 40,
      "dry": 10,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/enigma-berry.png"
  },
  {
    "id": 61,
    "name": "micle",
    "firmness": "soft",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "rock",
    "size": 41,
    "smoothness": 60,
    "soilDryness": 7,
    "flavors": {
      "spicy": 0,
      "dry": 40,
      "sweet": 10,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/micle-berry.png"
  },
  {
    "id": 62,
    "name": "custap",
    "firmness": "super-hard",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "ghost",
    "size": 267,
    "smoothness": 60,
    "soilDryness": 7,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 40,
      "bitter": 10,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/custap-berry.png"
  },
  {
    "id": 63,
    "name": "jaboca",
    "firmness": "soft",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "dragon",
    "size": 33,
    "smoothness": 60,
    "soilDryness": 7,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 40,
      "sour": 10
    },
    "spritePath": "/assets/items/berries/jaboca-berry.png"
  },
  {
    "id": 64,
    "name": "rowap",
    "firmness": "very-soft",
    "growthTime": 24,
    "maxHarvest": 5,
    "naturalGiftPower": 80,
    "naturalGiftType": "dark",
    "size": 52,
    "smoothness": 60,
    "soilDryness": 7,
    "flavors": {
      "spicy": 10,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 40
    },
    "spritePath": "/assets/items/berries/rowap-berry.png"
  },
  {
    "id": 65,
    "name": "kee",
    "firmness": "",
    "growthTime": 72,
    "maxHarvest": 8,
    "naturalGiftPower": 100,
    "naturalGiftType": "fairy",
    "size": 0,
    "smoothness": 0,
    "soilDryness": 0,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/kee-berry.png"
  },
  {
    "id": 66,
    "name": "maranga",
    "firmness": "",
    "growthTime": 72,
    "maxHarvest": 8,
    "naturalGiftPower": 100,
    "naturalGiftType": "dark",
    "size": 0,
    "smoothness": 0,
    "soilDryness": 0,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/maranga-berry.png"
  },
  {
    "id": 67,
    "name": "hopo",
    "firmness": "",
    "growthTime": 0,
    "maxHarvest": 0,
    "naturalGiftPower": 17,
    "naturalGiftType": "",
    "size": 0,
    "smoothness": 0,
    "soilDryness": 0,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/hopo-berry.png"
  },
  {
    "id": 68,
    "name": "roseli",
    "firmness": "",
    "growthTime": 0,
    "maxHarvest": 0,
    "naturalGiftPower": 0,
    "naturalGiftType": "",
    "size": 0,
    "smoothness": 0,
    "soilDryness": 0,
    "flavors": {
      "spicy": 0,
      "dry": 0,
      "sweet": 0,
      "bitter": 0,
      "sour": 0
    },
    "spritePath": "/assets/items/berries/roseli-berry.png"
  }
];

const BERRIES_BY_ID = new Map<number, BerryData>();
const BERRIES_BY_NAME = new Map<string, BerryData>();

for (const b of BERRIES) {
  BERRIES_BY_ID.set(b.id, b);
  BERRIES_BY_NAME.set(b.name.toLowerCase(), b);
}

export function getBerryById(id: number): BerryData | undefined {
  return BERRIES_BY_ID.get(id);
}

export function getBerryByName(name: string): BerryData | undefined {
  return BERRIES_BY_NAME.get(name.toLowerCase());
}

export function getAllBerries(): BerryData[] {
  return BERRIES;
}

export function getBerryCount(): number {
  return BERRIES.length;
}
