// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
import type { EvolutionData } from './schemas/index.ts';

export const EVOLUTIONS: EvolutionData[] = [
  {
    "species": "Bulbasaur",
    "targetSpecies": "Ivysaur",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Ivysaur",
    "targetSpecies": "Venusaur",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Charmander",
    "targetSpecies": "Charmeleon",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Charmeleon",
    "targetSpecies": "Charizard",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Squirtle",
    "targetSpecies": "Wartortle",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Wartortle",
    "targetSpecies": "Blastoise",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Caterpie",
    "targetSpecies": "Metapod",
    "trigger": "levelup",
    "conditions": {
      "level": 7
    }
  },
  {
    "species": "Metapod",
    "targetSpecies": "Butterfree",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Weedle",
    "targetSpecies": "Kakuna",
    "trigger": "levelup",
    "conditions": {
      "level": 7
    }
  },
  {
    "species": "Kakuna",
    "targetSpecies": "Beedrill",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Pidgey",
    "targetSpecies": "Pidgeotto",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Pidgeotto",
    "targetSpecies": "Pidgeot",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Rattata",
    "targetSpecies": "Raticate",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Rattata-Alola",
    "targetSpecies": "Raticate-Alola",
    "trigger": "levelup",
    "conditions": {
      "level": 20,
      "location": "at night"
    }
  },
  {
    "species": "Spearow",
    "targetSpecies": "Fearow",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Ekans",
    "targetSpecies": "Arbok",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Pichu",
    "targetSpecies": "Pikachu",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Pikachu",
    "targetSpecies": "Raichu",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Pikachu",
    "targetSpecies": "Raichu-Alola",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Sandshrew",
    "targetSpecies": "Sandslash",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Sandshrew-Alola",
    "targetSpecies": "Sandslash-Alola",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Nidoran-F",
    "targetSpecies": "Nidorina",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Nidorina",
    "targetSpecies": "Nidoqueen",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Nidoran-M",
    "targetSpecies": "Nidorino",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Nidorino",
    "targetSpecies": "Nidoking",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Cleffa",
    "targetSpecies": "Clefairy",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Clefairy",
    "targetSpecies": "Clefable",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Vulpix",
    "targetSpecies": "Ninetales",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Vulpix-Alola",
    "targetSpecies": "Ninetales-Alola",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Igglybuff",
    "targetSpecies": "Jigglypuff",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Jigglypuff",
    "targetSpecies": "Wigglytuff",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Zubat",
    "targetSpecies": "Golbat",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Oddish",
    "targetSpecies": "Gloom",
    "trigger": "levelup",
    "conditions": {
      "level": 21
    }
  },
  {
    "species": "Gloom",
    "targetSpecies": "Vileplume",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Paras",
    "targetSpecies": "Parasect",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Venonat",
    "targetSpecies": "Venomoth",
    "trigger": "levelup",
    "conditions": {
      "level": 31
    }
  },
  {
    "species": "Diglett",
    "targetSpecies": "Dugtrio",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Diglett-Alola",
    "targetSpecies": "Dugtrio-Alola",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Meowth",
    "targetSpecies": "Persian",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Meowth-Alola",
    "targetSpecies": "Persian-Alola",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Psyduck",
    "targetSpecies": "Golduck",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Mankey",
    "targetSpecies": "Primeape",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Growlithe",
    "targetSpecies": "Arcanine",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Growlithe-Hisui",
    "targetSpecies": "Arcanine-Hisui",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Poliwag",
    "targetSpecies": "Poliwhirl",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Poliwhirl",
    "targetSpecies": "Poliwrath",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Abra",
    "targetSpecies": "Kadabra",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Kadabra",
    "targetSpecies": "Alakazam",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Machop",
    "targetSpecies": "Machoke",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Machoke",
    "targetSpecies": "Machamp",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Bellsprout",
    "targetSpecies": "Weepinbell",
    "trigger": "levelup",
    "conditions": {
      "level": 21
    }
  },
  {
    "species": "Weepinbell",
    "targetSpecies": "Victreebel",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Tentacool",
    "targetSpecies": "Tentacruel",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Geodude",
    "targetSpecies": "Graveler",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Geodude-Alola",
    "targetSpecies": "Graveler-Alola",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Graveler",
    "targetSpecies": "Golem",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Graveler-Alola",
    "targetSpecies": "Golem-Alola",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Ponyta",
    "targetSpecies": "Rapidash",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Ponyta-Galar",
    "targetSpecies": "Rapidash-Galar",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Slowpoke",
    "targetSpecies": "Slowbro",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Slowpoke-Galar",
    "targetSpecies": "Slowbro-Galar",
    "trigger": "useItem",
    "conditions": {
      "item": "Galarica Cuff"
    }
  },
  {
    "species": "Magnemite",
    "targetSpecies": "Magneton",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Doduo",
    "targetSpecies": "Dodrio",
    "trigger": "levelup",
    "conditions": {
      "level": 31
    }
  },
  {
    "species": "Seel",
    "targetSpecies": "Dewgong",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Grimer",
    "targetSpecies": "Muk",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Grimer-Alola",
    "targetSpecies": "Muk-Alola",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Shellder",
    "targetSpecies": "Cloyster",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Gastly",
    "targetSpecies": "Haunter",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Haunter",
    "targetSpecies": "Gengar",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Drowzee",
    "targetSpecies": "Hypno",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Krabby",
    "targetSpecies": "Kingler",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Voltorb",
    "targetSpecies": "Electrode",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Voltorb-Hisui",
    "targetSpecies": "Electrode-Hisui",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Exeggcute",
    "targetSpecies": "Exeggutor",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Exeggcute",
    "targetSpecies": "Exeggutor-Alola",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Cubone",
    "targetSpecies": "Marowak",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Cubone",
    "targetSpecies": "Marowak-Alola",
    "trigger": "levelup",
    "conditions": {
      "level": 28,
      "location": "at night"
    }
  },
  {
    "species": "Tyrogue",
    "targetSpecies": "Hitmonlee",
    "trigger": "levelup",
    "conditions": {
      "level": 20,
      "location": "with an Atk stat > its Def stat"
    }
  },
  {
    "species": "Tyrogue",
    "targetSpecies": "Hitmonchan",
    "trigger": "levelup",
    "conditions": {
      "level": 20,
      "location": "with an Atk stat < its Def stat"
    }
  },
  {
    "species": "Koffing",
    "targetSpecies": "Weezing",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Koffing",
    "targetSpecies": "Weezing-Galar",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Rhyhorn",
    "targetSpecies": "Rhydon",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Happiny",
    "targetSpecies": "Chansey",
    "trigger": "levelHold",
    "conditions": {
      "item": "Oval Stone",
      "location": "during the day"
    }
  },
  {
    "species": "Horsea",
    "targetSpecies": "Seadra",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Goldeen",
    "targetSpecies": "Seaking",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Staryu",
    "targetSpecies": "Starmie",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Mime Jr.",
    "targetSpecies": "Mr. Mime",
    "trigger": "levelMove",
    "conditions": {
      "move": "Mimic"
    }
  },
  {
    "species": "Mime Jr.",
    "targetSpecies": "Mr. Mime-Galar",
    "trigger": "levelMove",
    "conditions": {
      "move": "Mimic"
    }
  },
  {
    "species": "Smoochum",
    "targetSpecies": "Jynx",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Elekid",
    "targetSpecies": "Electabuzz",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Magby",
    "targetSpecies": "Magmar",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Magikarp",
    "targetSpecies": "Gyarados",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Vaporeon",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Jolteon",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Flareon",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Omanyte",
    "targetSpecies": "Omastar",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Kabuto",
    "targetSpecies": "Kabutops",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Munchlax",
    "targetSpecies": "Snorlax",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Dratini",
    "targetSpecies": "Dragonair",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Dragonair",
    "targetSpecies": "Dragonite",
    "trigger": "levelup",
    "conditions": {
      "level": 55
    }
  },
  {
    "species": "Chikorita",
    "targetSpecies": "Bayleef",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Bayleef",
    "targetSpecies": "Meganium",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Cyndaquil",
    "targetSpecies": "Quilava",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Quilava",
    "targetSpecies": "Typhlosion",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Quilava",
    "targetSpecies": "Typhlosion-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Totodile",
    "targetSpecies": "Croconaw",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Croconaw",
    "targetSpecies": "Feraligatr",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Sentret",
    "targetSpecies": "Furret",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Hoothoot",
    "targetSpecies": "Noctowl",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Ledyba",
    "targetSpecies": "Ledian",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Spinarak",
    "targetSpecies": "Ariados",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Golbat",
    "targetSpecies": "Crobat",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Chinchou",
    "targetSpecies": "Lanturn",
    "trigger": "levelup",
    "conditions": {
      "level": 27
    }
  },
  {
    "species": "Togepi",
    "targetSpecies": "Togetic",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Natu",
    "targetSpecies": "Xatu",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Mareep",
    "targetSpecies": "Flaaffy",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Flaaffy",
    "targetSpecies": "Ampharos",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Gloom",
    "targetSpecies": "Bellossom",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Azurill",
    "targetSpecies": "Marill",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Marill",
    "targetSpecies": "Azumarill",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Bonsly",
    "targetSpecies": "Sudowoodo",
    "trigger": "levelMove",
    "conditions": {
      "move": "Mimic"
    }
  },
  {
    "species": "Poliwhirl",
    "targetSpecies": "Politoed",
    "trigger": "trade",
    "conditions": {
      "item": "King's Rock"
    }
  },
  {
    "species": "Hoppip",
    "targetSpecies": "Skiploom",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Skiploom",
    "targetSpecies": "Jumpluff",
    "trigger": "levelup",
    "conditions": {
      "level": 27
    }
  },
  {
    "species": "Sunkern",
    "targetSpecies": "Sunflora",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Wooper",
    "targetSpecies": "Quagsire",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Espeon",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "during the day"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Umbreon",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "at night"
    }
  },
  {
    "species": "Slowpoke",
    "targetSpecies": "Slowking",
    "trigger": "trade",
    "conditions": {
      "item": "King's Rock"
    }
  },
  {
    "species": "Slowpoke-Galar",
    "targetSpecies": "Slowking-Galar",
    "trigger": "useItem",
    "conditions": {
      "item": "Galarica Wreath"
    }
  },
  {
    "species": "Wynaut",
    "targetSpecies": "Wobbuffet",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Pineco",
    "targetSpecies": "Forretress",
    "trigger": "levelup",
    "conditions": {
      "level": 31
    }
  },
  {
    "species": "Onix",
    "targetSpecies": "Steelix",
    "trigger": "trade",
    "conditions": {
      "item": "Metal Coat"
    }
  },
  {
    "species": "Snubbull",
    "targetSpecies": "Granbull",
    "trigger": "levelup",
    "conditions": {
      "level": 23
    }
  },
  {
    "species": "Scyther",
    "targetSpecies": "Scizor",
    "trigger": "trade",
    "conditions": {
      "item": "Metal Coat"
    }
  },
  {
    "species": "Teddiursa",
    "targetSpecies": "Ursaring",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Slugma",
    "targetSpecies": "Magcargo",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Swinub",
    "targetSpecies": "Piloswine",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Remoraid",
    "targetSpecies": "Octillery",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Mantyke",
    "targetSpecies": "Mantine",
    "trigger": "levelExtra",
    "conditions": {
      "location": "with a Remoraid in party"
    }
  },
  {
    "species": "Houndour",
    "targetSpecies": "Houndoom",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Seadra",
    "targetSpecies": "Kingdra",
    "trigger": "trade",
    "conditions": {
      "item": "Dragon Scale"
    }
  },
  {
    "species": "Phanpy",
    "targetSpecies": "Donphan",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Porygon",
    "targetSpecies": "Porygon2",
    "trigger": "trade",
    "conditions": {
      "item": "Up-Grade"
    }
  },
  {
    "species": "Tyrogue",
    "targetSpecies": "Hitmontop",
    "trigger": "levelup",
    "conditions": {
      "level": 20,
      "location": "with an Atk stat equal to its Def stat"
    }
  },
  {
    "species": "Chansey",
    "targetSpecies": "Blissey",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Larvitar",
    "targetSpecies": "Pupitar",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Pupitar",
    "targetSpecies": "Tyranitar",
    "trigger": "levelup",
    "conditions": {
      "level": 55
    }
  },
  {
    "species": "Treecko",
    "targetSpecies": "Grovyle",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Grovyle",
    "targetSpecies": "Sceptile",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Torchic",
    "targetSpecies": "Combusken",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Combusken",
    "targetSpecies": "Blaziken",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Mudkip",
    "targetSpecies": "Marshtomp",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Marshtomp",
    "targetSpecies": "Swampert",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Poochyena",
    "targetSpecies": "Mightyena",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Zigzagoon",
    "targetSpecies": "Linoone",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Zigzagoon-Galar",
    "targetSpecies": "Linoone-Galar",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Wurmple",
    "targetSpecies": "Silcoon",
    "trigger": "levelup",
    "conditions": {
      "level": 7
    }
  },
  {
    "species": "Silcoon",
    "targetSpecies": "Beautifly",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Wurmple",
    "targetSpecies": "Cascoon",
    "trigger": "levelup",
    "conditions": {
      "level": 7
    }
  },
  {
    "species": "Cascoon",
    "targetSpecies": "Dustox",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Lotad",
    "targetSpecies": "Lombre",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Lombre",
    "targetSpecies": "Ludicolo",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Seedot",
    "targetSpecies": "Nuzleaf",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Nuzleaf",
    "targetSpecies": "Shiftry",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Taillow",
    "targetSpecies": "Swellow",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Wingull",
    "targetSpecies": "Pelipper",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Ralts",
    "targetSpecies": "Kirlia",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Kirlia",
    "targetSpecies": "Gardevoir",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Surskit",
    "targetSpecies": "Masquerain",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Shroomish",
    "targetSpecies": "Breloom",
    "trigger": "levelup",
    "conditions": {
      "level": 23
    }
  },
  {
    "species": "Slakoth",
    "targetSpecies": "Vigoroth",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Vigoroth",
    "targetSpecies": "Slaking",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Nincada",
    "targetSpecies": "Ninjask",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Nincada",
    "targetSpecies": "Shedinja",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Whismur",
    "targetSpecies": "Loudred",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Loudred",
    "targetSpecies": "Exploud",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Makuhita",
    "targetSpecies": "Hariyama",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Skitty",
    "targetSpecies": "Delcatty",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Aron",
    "targetSpecies": "Lairon",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Lairon",
    "targetSpecies": "Aggron",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Meditite",
    "targetSpecies": "Medicham",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Electrike",
    "targetSpecies": "Manectric",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Budew",
    "targetSpecies": "Roselia",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "during the day"
    }
  },
  {
    "species": "Gulpin",
    "targetSpecies": "Swalot",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Carvanha",
    "targetSpecies": "Sharpedo",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Wailmer",
    "targetSpecies": "Wailord",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Numel",
    "targetSpecies": "Camerupt",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Spoink",
    "targetSpecies": "Grumpig",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Trapinch",
    "targetSpecies": "Vibrava",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Vibrava",
    "targetSpecies": "Flygon",
    "trigger": "levelup",
    "conditions": {
      "level": 45
    }
  },
  {
    "species": "Cacnea",
    "targetSpecies": "Cacturne",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Swablu",
    "targetSpecies": "Altaria",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Barboach",
    "targetSpecies": "Whiscash",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Corphish",
    "targetSpecies": "Crawdaunt",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Baltoy",
    "targetSpecies": "Claydol",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Lileep",
    "targetSpecies": "Cradily",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Anorith",
    "targetSpecies": "Armaldo",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Feebas",
    "targetSpecies": "Milotic",
    "trigger": "trade",
    "conditions": {
      "item": "Prism Scale"
    }
  },
  {
    "species": "Shuppet",
    "targetSpecies": "Banette",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Duskull",
    "targetSpecies": "Dusclops",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Chingling",
    "targetSpecies": "Chimecho",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "at night"
    }
  },
  {
    "species": "Snorunt",
    "targetSpecies": "Glalie",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Spheal",
    "targetSpecies": "Sealeo",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Sealeo",
    "targetSpecies": "Walrein",
    "trigger": "levelup",
    "conditions": {
      "level": 44
    }
  },
  {
    "species": "Clamperl",
    "targetSpecies": "Huntail",
    "trigger": "trade",
    "conditions": {
      "item": "Deep Sea Tooth"
    }
  },
  {
    "species": "Clamperl",
    "targetSpecies": "Gorebyss",
    "trigger": "trade",
    "conditions": {
      "item": "Deep Sea Scale"
    }
  },
  {
    "species": "Bagon",
    "targetSpecies": "Shelgon",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Shelgon",
    "targetSpecies": "Salamence",
    "trigger": "levelup",
    "conditions": {
      "level": 50
    }
  },
  {
    "species": "Beldum",
    "targetSpecies": "Metang",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Metang",
    "targetSpecies": "Metagross",
    "trigger": "levelup",
    "conditions": {
      "level": 45
    }
  },
  {
    "species": "Turtwig",
    "targetSpecies": "Grotle",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Grotle",
    "targetSpecies": "Torterra",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Chimchar",
    "targetSpecies": "Monferno",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Monferno",
    "targetSpecies": "Infernape",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Piplup",
    "targetSpecies": "Prinplup",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Prinplup",
    "targetSpecies": "Empoleon",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Starly",
    "targetSpecies": "Staravia",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Staravia",
    "targetSpecies": "Staraptor",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Bidoof",
    "targetSpecies": "Bibarel",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Kricketot",
    "targetSpecies": "Kricketune",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Shinx",
    "targetSpecies": "Luxio",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Luxio",
    "targetSpecies": "Luxray",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Roselia",
    "targetSpecies": "Roserade",
    "trigger": "useItem",
    "conditions": {
      "item": "Shiny Stone"
    }
  },
  {
    "species": "Cranidos",
    "targetSpecies": "Rampardos",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Shieldon",
    "targetSpecies": "Bastiodon",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Burmy",
    "targetSpecies": "Wormadam",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Burmy",
    "targetSpecies": "Wormadam-Sandy",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Burmy",
    "targetSpecies": "Wormadam-Trash",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Burmy",
    "targetSpecies": "Mothim",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Combee",
    "targetSpecies": "Vespiquen",
    "trigger": "levelup",
    "conditions": {
      "level": 21
    }
  },
  {
    "species": "Buizel",
    "targetSpecies": "Floatzel",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Cherubi",
    "targetSpecies": "Cherrim",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Shellos",
    "targetSpecies": "Gastrodon",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Aipom",
    "targetSpecies": "Ambipom",
    "trigger": "levelMove",
    "conditions": {
      "move": "Double Hit"
    }
  },
  {
    "species": "Drifloon",
    "targetSpecies": "Drifblim",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Buneary",
    "targetSpecies": "Lopunny",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Misdreavus",
    "targetSpecies": "Mismagius",
    "trigger": "useItem",
    "conditions": {
      "item": "Dusk Stone"
    }
  },
  {
    "species": "Murkrow",
    "targetSpecies": "Honchkrow",
    "trigger": "useItem",
    "conditions": {
      "item": "Dusk Stone"
    }
  },
  {
    "species": "Glameow",
    "targetSpecies": "Purugly",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Stunky",
    "targetSpecies": "Skuntank",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Bronzor",
    "targetSpecies": "Bronzong",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Gible",
    "targetSpecies": "Gabite",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Gabite",
    "targetSpecies": "Garchomp",
    "trigger": "levelup",
    "conditions": {
      "level": 48
    }
  },
  {
    "species": "Riolu",
    "targetSpecies": "Lucario",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "during the day"
    }
  },
  {
    "species": "Hippopotas",
    "targetSpecies": "Hippowdon",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Skorupi",
    "targetSpecies": "Drapion",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Croagunk",
    "targetSpecies": "Toxicroak",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Finneon",
    "targetSpecies": "Lumineon",
    "trigger": "levelup",
    "conditions": {
      "level": 31
    }
  },
  {
    "species": "Snover",
    "targetSpecies": "Abomasnow",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Sneasel",
    "targetSpecies": "Weavile",
    "trigger": "levelHold",
    "conditions": {
      "item": "Razor Claw",
      "location": "at night"
    }
  },
  {
    "species": "Magneton",
    "targetSpecies": "Magnezone",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Lickitung",
    "targetSpecies": "Lickilicky",
    "trigger": "levelMove",
    "conditions": {
      "move": "Rollout"
    }
  },
  {
    "species": "Rhydon",
    "targetSpecies": "Rhyperior",
    "trigger": "trade",
    "conditions": {
      "item": "Protector"
    }
  },
  {
    "species": "Tangela",
    "targetSpecies": "Tangrowth",
    "trigger": "levelMove",
    "conditions": {
      "move": "Ancient Power"
    }
  },
  {
    "species": "Electabuzz",
    "targetSpecies": "Electivire",
    "trigger": "trade",
    "conditions": {
      "item": "Electirizer"
    }
  },
  {
    "species": "Magmar",
    "targetSpecies": "Magmortar",
    "trigger": "trade",
    "conditions": {
      "item": "Magmarizer"
    }
  },
  {
    "species": "Togetic",
    "targetSpecies": "Togekiss",
    "trigger": "useItem",
    "conditions": {
      "item": "Shiny Stone"
    }
  },
  {
    "species": "Yanma",
    "targetSpecies": "Yanmega",
    "trigger": "levelMove",
    "conditions": {
      "move": "Ancient Power"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Leafeon",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Glaceon",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Gligar",
    "targetSpecies": "Gliscor",
    "trigger": "levelHold",
    "conditions": {
      "item": "Razor Fang",
      "location": "at night"
    }
  },
  {
    "species": "Piloswine",
    "targetSpecies": "Mamoswine",
    "trigger": "levelMove",
    "conditions": {
      "move": "Ancient Power"
    }
  },
  {
    "species": "Porygon2",
    "targetSpecies": "Porygon-Z",
    "trigger": "trade",
    "conditions": {
      "item": "Dubious Disc"
    }
  },
  {
    "species": "Kirlia",
    "targetSpecies": "Gallade",
    "trigger": "useItem",
    "conditions": {
      "item": "Dawn Stone"
    }
  },
  {
    "species": "Nosepass",
    "targetSpecies": "Probopass",
    "trigger": "levelExtra",
    "conditions": {
      "location": "near a special magnetic field"
    }
  },
  {
    "species": "Dusclops",
    "targetSpecies": "Dusknoir",
    "trigger": "trade",
    "conditions": {
      "item": "Reaper Cloth"
    }
  },
  {
    "species": "Snorunt",
    "targetSpecies": "Froslass",
    "trigger": "useItem",
    "conditions": {
      "item": "Dawn Stone"
    }
  },
  {
    "species": "Snivy",
    "targetSpecies": "Servine",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Servine",
    "targetSpecies": "Serperior",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Tepig",
    "targetSpecies": "Pignite",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Pignite",
    "targetSpecies": "Emboar",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Oshawott",
    "targetSpecies": "Dewott",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Dewott",
    "targetSpecies": "Samurott",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Dewott",
    "targetSpecies": "Samurott-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Patrat",
    "targetSpecies": "Watchog",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Lillipup",
    "targetSpecies": "Herdier",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Herdier",
    "targetSpecies": "Stoutland",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Purrloin",
    "targetSpecies": "Liepard",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Pansage",
    "targetSpecies": "Simisage",
    "trigger": "useItem",
    "conditions": {
      "item": "Leaf Stone"
    }
  },
  {
    "species": "Pansear",
    "targetSpecies": "Simisear",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Panpour",
    "targetSpecies": "Simipour",
    "trigger": "useItem",
    "conditions": {
      "item": "Water Stone"
    }
  },
  {
    "species": "Munna",
    "targetSpecies": "Musharna",
    "trigger": "useItem",
    "conditions": {
      "item": "Moon Stone"
    }
  },
  {
    "species": "Pidove",
    "targetSpecies": "Tranquill",
    "trigger": "levelup",
    "conditions": {
      "level": 21
    }
  },
  {
    "species": "Tranquill",
    "targetSpecies": "Unfezant",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Blitzle",
    "targetSpecies": "Zebstrika",
    "trigger": "levelup",
    "conditions": {
      "level": 27
    }
  },
  {
    "species": "Roggenrola",
    "targetSpecies": "Boldore",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Boldore",
    "targetSpecies": "Gigalith",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Woobat",
    "targetSpecies": "Swoobat",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Drilbur",
    "targetSpecies": "Excadrill",
    "trigger": "levelup",
    "conditions": {
      "level": 31
    }
  },
  {
    "species": "Timburr",
    "targetSpecies": "Gurdurr",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Gurdurr",
    "targetSpecies": "Conkeldurr",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Tympole",
    "targetSpecies": "Palpitoad",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Palpitoad",
    "targetSpecies": "Seismitoad",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Sewaddle",
    "targetSpecies": "Swadloon",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Swadloon",
    "targetSpecies": "Leavanny",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Venipede",
    "targetSpecies": "Whirlipede",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Whirlipede",
    "targetSpecies": "Scolipede",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Cottonee",
    "targetSpecies": "Whimsicott",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Petilil",
    "targetSpecies": "Lilligant",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Petilil",
    "targetSpecies": "Lilligant-Hisui",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Sandile",
    "targetSpecies": "Krokorok",
    "trigger": "levelup",
    "conditions": {
      "level": 29
    }
  },
  {
    "species": "Krokorok",
    "targetSpecies": "Krookodile",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Darumaka",
    "targetSpecies": "Darmanitan",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Darumaka-Galar",
    "targetSpecies": "Darmanitan-Galar",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Dwebble",
    "targetSpecies": "Crustle",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Scraggy",
    "targetSpecies": "Scrafty",
    "trigger": "levelup",
    "conditions": {
      "level": 39
    }
  },
  {
    "species": "Yamask",
    "targetSpecies": "Cofagrigus",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Tirtouga",
    "targetSpecies": "Carracosta",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Archen",
    "targetSpecies": "Archeops",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Trubbish",
    "targetSpecies": "Garbodor",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Zorua",
    "targetSpecies": "Zoroark",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Zorua-Hisui",
    "targetSpecies": "Zoroark-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Minccino",
    "targetSpecies": "Cinccino",
    "trigger": "useItem",
    "conditions": {
      "item": "Shiny Stone"
    }
  },
  {
    "species": "Gothita",
    "targetSpecies": "Gothorita",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Gothorita",
    "targetSpecies": "Gothitelle",
    "trigger": "levelup",
    "conditions": {
      "level": 41
    }
  },
  {
    "species": "Solosis",
    "targetSpecies": "Duosion",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Duosion",
    "targetSpecies": "Reuniclus",
    "trigger": "levelup",
    "conditions": {
      "level": 41
    }
  },
  {
    "species": "Ducklett",
    "targetSpecies": "Swanna",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Vanillite",
    "targetSpecies": "Vanillish",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Vanillish",
    "targetSpecies": "Vanilluxe",
    "trigger": "levelup",
    "conditions": {
      "level": 47
    }
  },
  {
    "species": "Deerling",
    "targetSpecies": "Sawsbuck",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Karrablast",
    "targetSpecies": "Escavalier",
    "trigger": "trade",
    "conditions": {
      "location": "with a Shelmet"
    }
  },
  {
    "species": "Foongus",
    "targetSpecies": "Amoonguss",
    "trigger": "levelup",
    "conditions": {
      "level": 39
    }
  },
  {
    "species": "Frillish",
    "targetSpecies": "Jellicent",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Joltik",
    "targetSpecies": "Galvantula",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Ferroseed",
    "targetSpecies": "Ferrothorn",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Klink",
    "targetSpecies": "Klang",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Klang",
    "targetSpecies": "Klinklang",
    "trigger": "levelup",
    "conditions": {
      "level": 49
    }
  },
  {
    "species": "Tynamo",
    "targetSpecies": "Eelektrik",
    "trigger": "levelup",
    "conditions": {
      "level": 39
    }
  },
  {
    "species": "Eelektrik",
    "targetSpecies": "Eelektross",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Elgyem",
    "targetSpecies": "Beheeyem",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Litwick",
    "targetSpecies": "Lampent",
    "trigger": "levelup",
    "conditions": {
      "level": 41
    }
  },
  {
    "species": "Lampent",
    "targetSpecies": "Chandelure",
    "trigger": "useItem",
    "conditions": {
      "item": "Dusk Stone"
    }
  },
  {
    "species": "Axew",
    "targetSpecies": "Fraxure",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Fraxure",
    "targetSpecies": "Haxorus",
    "trigger": "levelup",
    "conditions": {
      "level": 48
    }
  },
  {
    "species": "Cubchoo",
    "targetSpecies": "Beartic",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Shelmet",
    "targetSpecies": "Accelgor",
    "trigger": "trade",
    "conditions": {
      "location": "with a Karrablast"
    }
  },
  {
    "species": "Mienfoo",
    "targetSpecies": "Mienshao",
    "trigger": "levelup",
    "conditions": {
      "level": 50
    }
  },
  {
    "species": "Golett",
    "targetSpecies": "Golurk",
    "trigger": "levelup",
    "conditions": {
      "level": 43
    }
  },
  {
    "species": "Pawniard",
    "targetSpecies": "Bisharp",
    "trigger": "levelup",
    "conditions": {
      "level": 52
    }
  },
  {
    "species": "Rufflet",
    "targetSpecies": "Braviary",
    "trigger": "levelup",
    "conditions": {
      "level": 54
    }
  },
  {
    "species": "Rufflet",
    "targetSpecies": "Braviary-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 54
    }
  },
  {
    "species": "Vullaby",
    "targetSpecies": "Mandibuzz",
    "trigger": "levelup",
    "conditions": {
      "level": 54
    }
  },
  {
    "species": "Deino",
    "targetSpecies": "Zweilous",
    "trigger": "levelup",
    "conditions": {
      "level": 50
    }
  },
  {
    "species": "Zweilous",
    "targetSpecies": "Hydreigon",
    "trigger": "levelup",
    "conditions": {
      "level": 64
    }
  },
  {
    "species": "Larvesta",
    "targetSpecies": "Volcarona",
    "trigger": "levelup",
    "conditions": {
      "level": 59
    }
  },
  {
    "species": "Chespin",
    "targetSpecies": "Quilladin",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Quilladin",
    "targetSpecies": "Chesnaught",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Fennekin",
    "targetSpecies": "Braixen",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Braixen",
    "targetSpecies": "Delphox",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Froakie",
    "targetSpecies": "Frogadier",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Frogadier",
    "targetSpecies": "Greninja",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Bunnelby",
    "targetSpecies": "Diggersby",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Fletchling",
    "targetSpecies": "Fletchinder",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Fletchinder",
    "targetSpecies": "Talonflame",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Scatterbug",
    "targetSpecies": "Spewpa",
    "trigger": "levelup",
    "conditions": {
      "level": 9
    }
  },
  {
    "species": "Spewpa",
    "targetSpecies": "Vivillon",
    "trigger": "levelup",
    "conditions": {
      "level": 12
    }
  },
  {
    "species": "Spewpa",
    "targetSpecies": "Vivillon-Fancy",
    "trigger": "levelup",
    "conditions": {
      "level": 12
    }
  },
  {
    "species": "Litleo",
    "targetSpecies": "Pyroar",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Flabébé",
    "targetSpecies": "Floette",
    "trigger": "levelup",
    "conditions": {
      "level": 19
    }
  },
  {
    "species": "Floette",
    "targetSpecies": "Florges",
    "trigger": "useItem",
    "conditions": {
      "item": "Shiny Stone"
    }
  },
  {
    "species": "Skiddo",
    "targetSpecies": "Gogoat",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Pancham",
    "targetSpecies": "Pangoro",
    "trigger": "levelup",
    "conditions": {
      "level": 32,
      "location": "with a Dark-type in the party"
    }
  },
  {
    "species": "Espurr",
    "targetSpecies": "Meowstic",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Espurr",
    "targetSpecies": "Meowstic-F",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Honedge",
    "targetSpecies": "Doublade",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Doublade",
    "targetSpecies": "Aegislash",
    "trigger": "useItem",
    "conditions": {
      "item": "Dusk Stone"
    }
  },
  {
    "species": "Spritzee",
    "targetSpecies": "Aromatisse",
    "trigger": "trade",
    "conditions": {
      "item": "Sachet"
    }
  },
  {
    "species": "Swirlix",
    "targetSpecies": "Slurpuff",
    "trigger": "trade",
    "conditions": {
      "item": "Whipped Dream"
    }
  },
  {
    "species": "Inkay",
    "targetSpecies": "Malamar",
    "trigger": "levelup",
    "conditions": {
      "level": 30,
      "location": "with the console turned upside-down"
    }
  },
  {
    "species": "Binacle",
    "targetSpecies": "Barbaracle",
    "trigger": "levelup",
    "conditions": {
      "level": 39
    }
  },
  {
    "species": "Skrelp",
    "targetSpecies": "Dragalge",
    "trigger": "levelup",
    "conditions": {
      "level": 48
    }
  },
  {
    "species": "Clauncher",
    "targetSpecies": "Clawitzer",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Helioptile",
    "targetSpecies": "Heliolisk",
    "trigger": "useItem",
    "conditions": {
      "item": "Sun Stone"
    }
  },
  {
    "species": "Tyrunt",
    "targetSpecies": "Tyrantrum",
    "trigger": "levelup",
    "conditions": {
      "level": 39,
      "location": "during the day"
    }
  },
  {
    "species": "Amaura",
    "targetSpecies": "Aurorus",
    "trigger": "levelup",
    "conditions": {
      "level": 39,
      "location": "at night"
    }
  },
  {
    "species": "Eevee",
    "targetSpecies": "Sylveon",
    "trigger": "levelExtra",
    "conditions": {
      "location": "with a Fairy-type move and two levels of Affection"
    }
  },
  {
    "species": "Goomy",
    "targetSpecies": "Sliggoo",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Goomy",
    "targetSpecies": "Sliggoo-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Sliggoo",
    "targetSpecies": "Goodra",
    "trigger": "levelup",
    "conditions": {
      "level": 50,
      "location": "during rain"
    }
  },
  {
    "species": "Sliggoo-Hisui",
    "targetSpecies": "Goodra-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 50,
      "location": "during rain"
    }
  },
  {
    "species": "Phantump",
    "targetSpecies": "Trevenant",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Pumpkaboo",
    "targetSpecies": "Gourgeist",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Pumpkaboo-Small",
    "targetSpecies": "Gourgeist-Small",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Pumpkaboo-Large",
    "targetSpecies": "Gourgeist-Large",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Pumpkaboo-Super",
    "targetSpecies": "Gourgeist-Super",
    "trigger": "trade",
    "conditions": {}
  },
  {
    "species": "Bergmite",
    "targetSpecies": "Avalugg",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Bergmite",
    "targetSpecies": "Avalugg-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 37
    }
  },
  {
    "species": "Noibat",
    "targetSpecies": "Noivern",
    "trigger": "levelup",
    "conditions": {
      "level": 48
    }
  },
  {
    "species": "Rowlet",
    "targetSpecies": "Dartrix",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Dartrix",
    "targetSpecies": "Decidueye",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Dartrix",
    "targetSpecies": "Decidueye-Hisui",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Litten",
    "targetSpecies": "Torracat",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Torracat",
    "targetSpecies": "Incineroar",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Popplio",
    "targetSpecies": "Brionne",
    "trigger": "levelup",
    "conditions": {
      "level": 17
    }
  },
  {
    "species": "Brionne",
    "targetSpecies": "Primarina",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Pikipek",
    "targetSpecies": "Trumbeak",
    "trigger": "levelup",
    "conditions": {
      "level": 14
    }
  },
  {
    "species": "Trumbeak",
    "targetSpecies": "Toucannon",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Yungoos",
    "targetSpecies": "Gumshoos",
    "trigger": "levelup",
    "conditions": {
      "level": 20,
      "location": "during the day"
    }
  },
  {
    "species": "Grubbin",
    "targetSpecies": "Charjabug",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Charjabug",
    "targetSpecies": "Vikavolt",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Crabrawler",
    "targetSpecies": "Crabominable",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Cutiefly",
    "targetSpecies": "Ribombee",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Rockruff",
    "targetSpecies": "Lycanroc",
    "trigger": "levelup",
    "conditions": {
      "level": 25,
      "location": "during the day"
    }
  },
  {
    "species": "Rockruff",
    "targetSpecies": "Lycanroc-Midnight",
    "trigger": "levelup",
    "conditions": {
      "level": 25,
      "location": "at night"
    }
  },
  {
    "species": "Rockruff-Dusk",
    "targetSpecies": "Lycanroc-Dusk",
    "trigger": "levelup",
    "conditions": {
      "level": 25,
      "location": "from a special Rockruff during the evening"
    }
  },
  {
    "species": "Mareanie",
    "targetSpecies": "Toxapex",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Mudbray",
    "targetSpecies": "Mudsdale",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Dewpider",
    "targetSpecies": "Araquanid",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Fomantis",
    "targetSpecies": "Lurantis",
    "trigger": "levelup",
    "conditions": {
      "level": 34,
      "location": "during the day"
    }
  },
  {
    "species": "Morelull",
    "targetSpecies": "Shiinotic",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Salandit",
    "targetSpecies": "Salazzle",
    "trigger": "levelup",
    "conditions": {
      "level": 33
    }
  },
  {
    "species": "Stufful",
    "targetSpecies": "Bewear",
    "trigger": "levelup",
    "conditions": {
      "level": 27
    }
  },
  {
    "species": "Bounsweet",
    "targetSpecies": "Steenee",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Steenee",
    "targetSpecies": "Tsareena",
    "trigger": "levelMove",
    "conditions": {
      "move": "Stomp"
    }
  },
  {
    "species": "Wimpod",
    "targetSpecies": "Golisopod",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Sandygast",
    "targetSpecies": "Palossand",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Type: Null",
    "targetSpecies": "Silvally",
    "trigger": "levelFriendship",
    "conditions": {}
  },
  {
    "species": "Jangmo-o",
    "targetSpecies": "Hakamo-o",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Hakamo-o",
    "targetSpecies": "Kommo-o",
    "trigger": "levelup",
    "conditions": {
      "level": 45
    }
  },
  {
    "species": "Cosmog",
    "targetSpecies": "Cosmoem",
    "trigger": "levelup",
    "conditions": {
      "level": 43
    }
  },
  {
    "species": "Cosmoem",
    "targetSpecies": "Solgaleo",
    "trigger": "levelup",
    "conditions": {
      "level": 53
    }
  },
  {
    "species": "Cosmoem",
    "targetSpecies": "Lunala",
    "trigger": "levelup",
    "conditions": {
      "level": 53
    }
  },
  {
    "species": "Poipole",
    "targetSpecies": "Naganadel",
    "trigger": "levelMove",
    "conditions": {
      "move": "Dragon Pulse"
    }
  },
  {
    "species": "Grookey",
    "targetSpecies": "Thwackey",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Thwackey",
    "targetSpecies": "Rillaboom",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Scorbunny",
    "targetSpecies": "Raboot",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Raboot",
    "targetSpecies": "Cinderace",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Sobble",
    "targetSpecies": "Drizzile",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Drizzile",
    "targetSpecies": "Inteleon",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Skwovet",
    "targetSpecies": "Greedent",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Rookidee",
    "targetSpecies": "Corvisquire",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Corvisquire",
    "targetSpecies": "Corviknight",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Blipbug",
    "targetSpecies": "Dottler",
    "trigger": "levelup",
    "conditions": {
      "level": 10
    }
  },
  {
    "species": "Dottler",
    "targetSpecies": "Orbeetle",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Nickit",
    "targetSpecies": "Thievul",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Gossifleur",
    "targetSpecies": "Eldegoss",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Wooloo",
    "targetSpecies": "Dubwool",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Chewtle",
    "targetSpecies": "Drednaw",
    "trigger": "levelup",
    "conditions": {
      "level": 22
    }
  },
  {
    "species": "Yamper",
    "targetSpecies": "Boltund",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Rolycoly",
    "targetSpecies": "Carkol",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Carkol",
    "targetSpecies": "Coalossal",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Applin",
    "targetSpecies": "Flapple",
    "trigger": "useItem",
    "conditions": {
      "item": "Tart Apple"
    }
  },
  {
    "species": "Applin",
    "targetSpecies": "Appletun",
    "trigger": "useItem",
    "conditions": {
      "item": "Sweet Apple"
    }
  },
  {
    "species": "Silicobra",
    "targetSpecies": "Sandaconda",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Arrokuda",
    "targetSpecies": "Barraskewda",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Toxel",
    "targetSpecies": "Toxtricity",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Toxel",
    "targetSpecies": "Toxtricity-Low-Key",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Sizzlipede",
    "targetSpecies": "Centiskorch",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Clobbopus",
    "targetSpecies": "Grapploct",
    "trigger": "levelMove",
    "conditions": {
      "move": "Taunt"
    }
  },
  {
    "species": "Sinistea",
    "targetSpecies": "Polteageist",
    "trigger": "useItem",
    "conditions": {
      "item": "Cracked Pot"
    }
  },
  {
    "species": "Sinistea-Antique",
    "targetSpecies": "Polteageist-Antique",
    "trigger": "useItem",
    "conditions": {
      "item": "Chipped Pot"
    }
  },
  {
    "species": "Hatenna",
    "targetSpecies": "Hattrem",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Hattrem",
    "targetSpecies": "Hatterene",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Impidimp",
    "targetSpecies": "Morgrem",
    "trigger": "levelup",
    "conditions": {
      "level": 32
    }
  },
  {
    "species": "Morgrem",
    "targetSpecies": "Grimmsnarl",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Linoone-Galar",
    "targetSpecies": "Obstagoon",
    "trigger": "levelup",
    "conditions": {
      "level": 35,
      "location": "at night"
    }
  },
  {
    "species": "Meowth-Galar",
    "targetSpecies": "Perrserker",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Corsola-Galar",
    "targetSpecies": "Cursola",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Farfetch’d-Galar",
    "targetSpecies": "Sirfetch’d",
    "trigger": "other",
    "conditions": {
      "location": "Land 3 critical hits in 1 battle"
    }
  },
  {
    "species": "Mr. Mime-Galar",
    "targetSpecies": "Mr. Rime",
    "trigger": "levelup",
    "conditions": {
      "level": 42
    }
  },
  {
    "species": "Yamask-Galar",
    "targetSpecies": "Runerigus",
    "trigger": "other",
    "conditions": {
      "location": "Have 49+ HP lost and walk under stone sculpture in Dusty Bowl"
    }
  },
  {
    "species": "Milcery",
    "targetSpecies": "Alcremie",
    "trigger": "other",
    "conditions": {
      "location": "spin while holding a Sweet"
    }
  },
  {
    "species": "Snom",
    "targetSpecies": "Frosmoth",
    "trigger": "levelFriendship",
    "conditions": {
      "location": "at night"
    }
  },
  {
    "species": "Cufant",
    "targetSpecies": "Copperajah",
    "trigger": "levelup",
    "conditions": {
      "level": 34
    }
  },
  {
    "species": "Dreepy",
    "targetSpecies": "Drakloak",
    "trigger": "levelup",
    "conditions": {
      "level": 50
    }
  },
  {
    "species": "Drakloak",
    "targetSpecies": "Dragapult",
    "trigger": "levelup",
    "conditions": {
      "level": 60
    }
  },
  {
    "species": "Kubfu",
    "targetSpecies": "Urshifu",
    "trigger": "other",
    "conditions": {
      "location": "Defeat the Single Strike Tower"
    }
  },
  {
    "species": "Kubfu",
    "targetSpecies": "Urshifu-Rapid-Strike",
    "trigger": "other",
    "conditions": {
      "location": "Defeat the Rapid Strike Tower"
    }
  },
  {
    "species": "Stantler",
    "targetSpecies": "Wyrdeer",
    "trigger": "other",
    "conditions": {
      "location": "Use Agile style Psyshield Bash 20 times"
    }
  },
  {
    "species": "Scyther",
    "targetSpecies": "Kleavor",
    "trigger": "useItem",
    "conditions": {
      "location": "Black Augurite"
    }
  },
  {
    "species": "Ursaring",
    "targetSpecies": "Ursaluna",
    "trigger": "other",
    "conditions": {
      "location": "Peat Block when there's a full moon"
    }
  },
  {
    "species": "Basculin-White-Striped",
    "targetSpecies": "Basculegion",
    "trigger": "other",
    "conditions": {
      "location": "Receive 294+ recoil without fainting"
    }
  },
  {
    "species": "Basculin-White-Striped",
    "targetSpecies": "Basculegion-F",
    "trigger": "other",
    "conditions": {
      "location": "Receive 294+ recoil without fainting"
    }
  },
  {
    "species": "Sneasel-Hisui",
    "targetSpecies": "Sneasler",
    "trigger": "levelHold",
    "conditions": {
      "item": "Razor Claw",
      "location": "during the day"
    }
  },
  {
    "species": "Qwilfish-Hisui",
    "targetSpecies": "Overqwil",
    "trigger": "other",
    "conditions": {
      "location": "Use Strong style Barb Barrage 20 times"
    }
  },
  {
    "species": "Sprigatito",
    "targetSpecies": "Floragato",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Floragato",
    "targetSpecies": "Meowscarada",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Fuecoco",
    "targetSpecies": "Crocalor",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Crocalor",
    "targetSpecies": "Skeledirge",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Quaxly",
    "targetSpecies": "Quaxwell",
    "trigger": "levelup",
    "conditions": {
      "level": 16
    }
  },
  {
    "species": "Quaxwell",
    "targetSpecies": "Quaquaval",
    "trigger": "levelup",
    "conditions": {
      "level": 36
    }
  },
  {
    "species": "Lechonk",
    "targetSpecies": "Oinkologne",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Lechonk",
    "targetSpecies": "Oinkologne-F",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Tarountula",
    "targetSpecies": "Spidops",
    "trigger": "levelup",
    "conditions": {
      "level": 15
    }
  },
  {
    "species": "Nymble",
    "targetSpecies": "Lokix",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Pawmi",
    "targetSpecies": "Pawmo",
    "trigger": "levelup",
    "conditions": {
      "level": 18
    }
  },
  {
    "species": "Pawmo",
    "targetSpecies": "Pawmot",
    "trigger": "other",
    "conditions": {
      "location": "walk 1000 steps in Let's Go"
    }
  },
  {
    "species": "Tandemaus",
    "targetSpecies": "Maushold",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Tandemaus",
    "targetSpecies": "Maushold-Four",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Fidough",
    "targetSpecies": "Dachsbun",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Smoliv",
    "targetSpecies": "Dolliv",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Dolliv",
    "targetSpecies": "Arboliva",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Nacli",
    "targetSpecies": "Naclstack",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Naclstack",
    "targetSpecies": "Garganacl",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Charcadet",
    "targetSpecies": "Armarouge",
    "trigger": "useItem",
    "conditions": {
      "item": "Auspicious Armor"
    }
  },
  {
    "species": "Charcadet",
    "targetSpecies": "Ceruledge",
    "trigger": "useItem",
    "conditions": {
      "item": "Malicious Armor"
    }
  },
  {
    "species": "Tadbulb",
    "targetSpecies": "Bellibolt",
    "trigger": "useItem",
    "conditions": {
      "item": "Thunder Stone"
    }
  },
  {
    "species": "Wattrel",
    "targetSpecies": "Kilowattrel",
    "trigger": "levelup",
    "conditions": {
      "level": 25
    }
  },
  {
    "species": "Maschiff",
    "targetSpecies": "Mabosstiff",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Shroodle",
    "targetSpecies": "Grafaiai",
    "trigger": "levelup",
    "conditions": {
      "level": 28
    }
  },
  {
    "species": "Bramblin",
    "targetSpecies": "Brambleghast",
    "trigger": "other",
    "conditions": {
      "location": "Walk 1000 steps in Let's Go"
    }
  },
  {
    "species": "Toedscool",
    "targetSpecies": "Toedscruel",
    "trigger": "levelup",
    "conditions": {
      "level": 30
    }
  },
  {
    "species": "Capsakid",
    "targetSpecies": "Scovillain",
    "trigger": "useItem",
    "conditions": {
      "item": "Fire Stone"
    }
  },
  {
    "species": "Rellor",
    "targetSpecies": "Rabsca",
    "trigger": "other",
    "conditions": {
      "location": "walk 1000 steps in Let's Go"
    }
  },
  {
    "species": "Flittle",
    "targetSpecies": "Espathra",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Tinkatink",
    "targetSpecies": "Tinkatuff",
    "trigger": "levelup",
    "conditions": {
      "level": 24
    }
  },
  {
    "species": "Tinkatuff",
    "targetSpecies": "Tinkaton",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Wiglett",
    "targetSpecies": "Wugtrio",
    "trigger": "levelup",
    "conditions": {
      "level": 26
    }
  },
  {
    "species": "Finizen",
    "targetSpecies": "Palafin",
    "trigger": "levelup",
    "conditions": {
      "level": 38
    }
  },
  {
    "species": "Varoom",
    "targetSpecies": "Revavroom",
    "trigger": "levelup",
    "conditions": {
      "level": 40
    }
  },
  {
    "species": "Glimmet",
    "targetSpecies": "Glimmora",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Greavard",
    "targetSpecies": "Houndstone",
    "trigger": "levelup",
    "conditions": {
      "level": 30,
      "location": "at night"
    }
  },
  {
    "species": "Cetoddle",
    "targetSpecies": "Cetitan",
    "trigger": "useItem",
    "conditions": {
      "item": "Ice Stone"
    }
  },
  {
    "species": "Primeape",
    "targetSpecies": "Annihilape",
    "trigger": "other",
    "conditions": {
      "location": "Use Rage Fist 20 times and level-up"
    }
  },
  {
    "species": "Wooper-Paldea",
    "targetSpecies": "Clodsire",
    "trigger": "levelup",
    "conditions": {
      "level": 20
    }
  },
  {
    "species": "Girafarig",
    "targetSpecies": "Farigiraf",
    "trigger": "levelMove",
    "conditions": {
      "move": "Twin Beam"
    }
  },
  {
    "species": "Dunsparce",
    "targetSpecies": "Dudunsparce",
    "trigger": "levelMove",
    "conditions": {
      "move": "Hyper Drill"
    }
  },
  {
    "species": "Dunsparce",
    "targetSpecies": "Dudunsparce-Three-Segment",
    "trigger": "levelMove",
    "conditions": {
      "move": "Hyper Drill"
    }
  },
  {
    "species": "Bisharp",
    "targetSpecies": "Kingambit",
    "trigger": "other",
    "conditions": {
      "location": "Defeat 3 Bisharp leading Pawniard and level-up"
    }
  },
  {
    "species": "Frigibax",
    "targetSpecies": "Arctibax",
    "trigger": "levelup",
    "conditions": {
      "level": 35
    }
  },
  {
    "species": "Arctibax",
    "targetSpecies": "Baxcalibur",
    "trigger": "levelup",
    "conditions": {
      "level": 54
    }
  },
  {
    "species": "Gimmighoul",
    "targetSpecies": "Gholdengo",
    "trigger": "other",
    "conditions": {
      "location": "Level up with 999 Coins in the bag"
    }
  },
  {
    "species": "Applin",
    "targetSpecies": "Dipplin",
    "trigger": "useItem",
    "conditions": {
      "item": "Syrupy Apple"
    }
  },
  {
    "species": "Poltchageist",
    "targetSpecies": "Sinistcha",
    "trigger": "useItem",
    "conditions": {
      "item": "Unremarkable Teacup"
    }
  },
  {
    "species": "Poltchageist-Artisan",
    "targetSpecies": "Sinistcha-Masterpiece",
    "trigger": "useItem",
    "conditions": {
      "item": "Masterpiece Teacup"
    }
  },
  {
    "species": "Duraludon",
    "targetSpecies": "Archaludon",
    "trigger": "useItem",
    "conditions": {
      "item": "Metal Alloy"
    }
  },
  {
    "species": "Dipplin",
    "targetSpecies": "Hydrapple",
    "trigger": "levelMove",
    "conditions": {
      "move": "Dragon Cheer"
    }
  }
];

const EVOS_BY_SPECIES = new Map<string, EvolutionData[]>();

for (const e of EVOLUTIONS) {
  const key = e.species.toLowerCase();
  if (!EVOS_BY_SPECIES.has(key)) EVOS_BY_SPECIES.set(key, []);
  EVOS_BY_SPECIES.get(key)!.push(e);
}

export function getEvolutionsForSpecies(species: string): EvolutionData[] {
  return EVOS_BY_SPECIES.get(species.toLowerCase()) || [];
}

export function getAllEvolutions(): EvolutionData[] {
  return EVOLUTIONS;
}

export function getEvolutionCount(): number {
  return EVOLUTIONS.length;
}
