// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
export { TYPES, TYPE_NAMES, getTypeByName, getTypeById, getEffectiveness } from './types.ts';
export { SPECIES, getSpeciesById, getSpeciesByName, getAllSpecies, getSpeciesCount } from './species.ts';
export { MOVES, getMoveById, getMoveByName, getAllMoves, getMoveCount } from './moves.ts';
export { ABILITIES, getAbilityById, getAbilityByName, getAllAbilities, getAbilityCount } from './abilities.ts';
export { ITEMS, getItemById, getItemByName, getAllItems, getItemCount } from './items.ts';
export { EVOLUTIONS, getEvolutionsForSpecies, getAllEvolutions, getEvolutionCount } from './evolutions.ts';
export { BERRIES, getBerryById, getBerryByName, getAllBerries, getBerryCount } from './berries.ts';
export { MEGA_EVOLUTIONS, getMegaByStone, getMegasForSpecies, getAllMegaEvolutions } from './megaEvolutions.ts';
export { MEGA_STONES, getMegaStoneById, getMegaStoneByName, getMegaStonesForSpecies, getAllMegaStones } from './megaStones.ts';

export type { PokemonSpeciesData, MoveData, AbilityData, ItemData, TypeEffectiveness, EvolutionData, PokemonType, BerryData, MegaEvolutionData, MegaStoneData } from './schemas/index.ts';
