// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
import type { MegaStoneData } from './schemas/index.ts';

export const MEGA_STONES: MegaStoneData[] = [
  {
    "id": 674,
    "name": "Abomasite",
    "desc": "If held by an Abomasnow, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Abomasnow, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Abomasone",
    "spritePath": "/assets/items/icons/abomasite.png"
  },
  {
    "id": 677,
    "name": "Absolite",
    "desc": "If held by an Absol, this item allows it to Mega Evolve into Mega Absol in battle.",
    "shortDesc": "If held by an Absol, this item allows it to Mega Evolve into Mega Absol in battle.",
    "generation": 6,
    "targetSpecies": "Absol",
    "spritePath": "/assets/items/icons/absolite.png"
  },
  {
    "id": 672,
    "name": "Aerodactylite",
    "desc": "If held by an Aerodactyl, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Aerodactyl, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Aerodactyl",
    "spritePath": "/assets/items/icons/aerodactylite.png"
  },
  {
    "id": 667,
    "name": "Aggronite",
    "desc": "If held by an Aggron, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Aggron, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Aggron",
    "spritePath": "/assets/items/icons/aggronite.png"
  },
  {
    "id": 679,
    "name": "Alakazite",
    "desc": "If held by an Alakazam, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Alakazam, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Alakazam",
    "spritePath": "/assets/items/icons/alakazite.png"
  },
  {
    "id": 755,
    "name": "Altarianite",
    "desc": "If held by an Altaria, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Altaria, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Altaria",
    "spritePath": "/assets/items/icons/altarianite.png"
  },
  {
    "id": 658,
    "name": "Ampharosite",
    "desc": "If held by an Ampharos, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Ampharos, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Amphaross",
    "spritePath": "/assets/items/icons/ampharosite.png"
  },
  {
    "id": 757,
    "name": "Audinite",
    "desc": "If held by an Audino, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by an Audino, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Audino",
    "spritePath": "/assets/items/icons/audinite.png"
  },
  {
    "id": 668,
    "name": "Banettite",
    "desc": "If held by a Banette, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Banette, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Banette",
    "spritePath": "/assets/items/icons/banettite.png"
  },
  {
    "id": 770,
    "name": "Beedrillite",
    "desc": "If held by a Beedrill, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Beedrill, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Beedrill",
    "spritePath": "/assets/items/icons/beedrillite.png"
  },
  {
    "id": 661,
    "name": "Blastoisinite",
    "desc": "If held by a Blastoise, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Blastoise, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Blastoise",
    "spritePath": "/assets/items/icons/blastoisinite.png"
  },
  {
    "id": 664,
    "name": "Blazikenite",
    "desc": "If held by a Blaziken, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Blaziken, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Blaziken",
    "spritePath": "/assets/items/icons/blazikenite.png"
  },
  {
    "id": 767,
    "name": "Cameruptite",
    "desc": "If held by a Camerupt, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Camerupt, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Camerupt",
    "spritePath": "/assets/items/icons/cameruptite.png"
  },
  {
    "id": 660,
    "name": "Charizardite X",
    "desc": "If held by a Charizard, this item allows it to Mega Evolve into Mega Charizard X.",
    "shortDesc": "If held by a Charizard, this item allows it to Mega Evolve into Mega Charizard X.",
    "generation": 6,
    "targetSpecies": "Charizard",
    "spritePath": "/assets/items/icons/charizardite-x.png"
  },
  {
    "id": 678,
    "name": "Charizardite Y",
    "desc": "If held by a Charizard, this item allows it to Mega Evolve into Mega Charizard Y.",
    "shortDesc": "If held by a Charizard, this item allows it to Mega Evolve into Mega Charizard Y.",
    "generation": 6,
    "targetSpecies": "Charizard",
    "spritePath": "/assets/items/icons/charizardite-y.png"
  },
  {
    "id": 764,
    "name": "Diancite",
    "desc": "If held by a Diancie, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Diancie, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Diancie",
    "spritePath": "/assets/items/icons/diancite.png"
  },
  {
    "id": 683,
    "name": "Garchompite",
    "desc": "If held by a Garchomp, this item allows it to Mega Evolve into Mega Garchomp.",
    "shortDesc": "If held by a Garchomp, this item allows it to Mega Evolve into Mega Garchomp.",
    "generation": 6,
    "targetSpecies": "Garchomp",
    "spritePath": "/assets/items/icons/garchompite.png"
  },
  {
    "id": 657,
    "name": "Gardevoirite",
    "desc": "If held by a Gardevoir, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Gardevoir, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Gardevoir",
    "spritePath": "/assets/items/icons/gardevoirite.png"
  },
  {
    "id": 656,
    "name": "Gengarite",
    "desc": "If held by a Gengar, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Gengar, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Gengar",
    "spritePath": "/assets/items/icons/gengarite.png"
  },
  {
    "id": 676,
    "name": "Gyaradosite",
    "desc": "If held by a Gyarados, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Gyarados, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Gyarados",
    "spritePath": "/assets/items/icons/gyaradosite.png"
  },
  {
    "id": 680,
    "name": "Heracronite",
    "desc": "If held by a Heracross, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Heracross, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Heracross",
    "spritePath": "/assets/items/icons/heracronite.png"
  },
  {
    "id": 666,
    "name": "Houndoominite",
    "desc": "If held by a Houndoom, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Houndoom, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Houndoom",
    "spritePath": "/assets/items/icons/houndoominite.png"
  },
  {
    "id": 675,
    "name": "Kangaskhanite",
    "desc": "If held by a Kangaskhan, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Kangaskhan, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Kangaskhan",
    "spritePath": "/assets/items/icons/kangaskhanite.png"
  },
  {
    "id": 684,
    "name": "Latiasite",
    "desc": "If held by a Latias, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Latias, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Latias",
    "spritePath": "/assets/items/icons/latiasite.png"
  },
  {
    "id": 685,
    "name": "Latiosite",
    "desc": "If held by a Latios, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Latios, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Latios",
    "spritePath": "/assets/items/icons/latiosite.png"
  },
  {
    "id": 768,
    "name": "Lopunnite",
    "desc": "If held by a Lopunny, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Lopunny, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Lopunny",
    "spritePath": "/assets/items/icons/lopunnite.png"
  },
  {
    "id": 673,
    "name": "Lucarionite",
    "desc": "If held by a Lucario, this item allows it to Mega Evolve into Mega Lucario in battle.",
    "shortDesc": "If held by a Lucario, this item allows it to Mega Evolve into Mega Lucario in battle.",
    "generation": 6,
    "targetSpecies": "Lucario",
    "spritePath": "/assets/items/icons/lucarionite.png"
  },
  {
    "id": 681,
    "name": "Mawilite",
    "desc": "If held by a Mawile, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Mawile, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Mawile",
    "spritePath": "/assets/items/icons/mawilite.png"
  },
  {
    "id": 665,
    "name": "Medichamite",
    "desc": "If held by a Medicham, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Medicham, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Medicham",
    "spritePath": "/assets/items/icons/medichamite.png"
  },
  {
    "id": 662,
    "name": "Mewtwonite X",
    "desc": "If held by a Mewtwo, this item allows it to Mega Evolve into Mega Mewtwo X in battle.",
    "shortDesc": "If held by a Mewtwo, this item allows it to Mega Evolve into Mega Mewtwo X in battle.",
    "generation": 6,
    "targetSpecies": "Mewtwo",
    "spritePath": "/assets/items/icons/mewtwonite-x.png"
  },
  {
    "id": 663,
    "name": "Mewtwonite Y",
    "desc": "If held by a Mewtwo, this item allows it to Mega Evolve into Mega Mewtwo Y in battle.",
    "shortDesc": "If held by a Mewtwo, this item allows it to Mega Evolve into Mega Mewtwo Y in battle.",
    "generation": 6,
    "targetSpecies": "Mewtwo",
    "spritePath": "/assets/items/icons/mewtwonite-y.png"
  },
  {
    "id": 762,
    "name": "Pidgeotite",
    "desc": "If held by a Pidgeot, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Pidgeot, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Pidgeot",
    "spritePath": "/assets/items/icons/pidgeotite.png"
  },
  {
    "id": 671,
    "name": "Pinsirite",
    "desc": "If held by a Pinsir, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Pinsir, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Pinsir",
    "spritePath": "/assets/items/icons/pinsirite.png"
  },
  {
    "id": 754,
    "name": "Sablenite",
    "desc": "If held by a Sableye, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Sableye, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Sableye",
    "spritePath": "/assets/items/icons/sablenite.png"
  },
  {
    "id": 753,
    "name": "Sceptilite",
    "desc": "If held by a Sceptile, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Sceptile, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Sceptile",
    "spritePath": "/assets/items/icons/sceptilite.png"
  },
  {
    "id": 670,
    "name": "Scizorite",
    "desc": "If held by a Scizor, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Scizor, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Scizor",
    "spritePath": "/assets/items/icons/scizorite.png"
  },
  {
    "id": 759,
    "name": "Sharpedonite",
    "desc": "If held by a Sharpedo, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Sharpedo, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Sharpedo",
    "spritePath": "/assets/items/icons/sharpedonite.png"
  },
  {
    "id": 760,
    "name": "Slowbronite",
    "desc": "If held by a Slowbro, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Slowbro, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Slowbro",
    "spritePath": "/assets/items/icons/slowbronite.png"
  },
  {
    "id": 761,
    "name": "Steelixite",
    "desc": "If held by a Steelix, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Steelix, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Steelix",
    "spritePath": "/assets/items/icons/steelixite.png"
  },
  {
    "id": 752,
    "name": "Swampertite",
    "desc": "If held by a Swampert, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Swampert, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Swampert",
    "spritePath": "/assets/items/icons/swampertite.png"
  },
  {
    "id": 669,
    "name": "Tyranitarite",
    "desc": "If held by a Tyranitar, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Tyranitar, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Tyranitar",
    "spritePath": "/assets/items/icons/tyranitarite.png"
  },
  {
    "id": 659,
    "name": "Venusaurite",
    "desc": "If held by a Venusaur, this item allows it to Mega Evolve in battle.",
    "shortDesc": "If held by a Venusaur, this item allows it to Mega Evolve in battle.",
    "generation": 6,
    "targetSpecies": "Venusaur",
    "spritePath": "/assets/items/icons/venusaurite.png"
  }
];

const STONES_BY_ID = new Map<number, MegaStoneData>();
const STONES_BY_NAME = new Map<string, MegaStoneData>();
const STONES_BY_SPECIES = new Map<string, MegaStoneData[]>();

for (const s of MEGA_STONES) {
  STONES_BY_ID.set(s.id, s);
  STONES_BY_NAME.set(s.name.toLowerCase(), s);
  const key = s.targetSpecies.toLowerCase();
  if (!STONES_BY_SPECIES.has(key)) STONES_BY_SPECIES.set(key, []);
  STONES_BY_SPECIES.get(key)!.push(s);
}

export function getMegaStoneById(id: number): MegaStoneData | undefined {
  return STONES_BY_ID.get(id);
}

export function getMegaStoneByName(name: string): MegaStoneData | undefined {
  return STONES_BY_NAME.get(name.toLowerCase());
}

export function getMegaStonesForSpecies(species: string): MegaStoneData[] {
  return STONES_BY_SPECIES.get(species.toLowerCase()) || [];
}

export function getAllMegaStones(): MegaStoneData[] {
  return MEGA_STONES;
}
