// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
import type { MegaEvolutionData } from './schemas/index.ts';

export const MEGA_EVOLUTIONS: MegaEvolutionData[] = [
  {
    "baseSpecies": "Venusaur",
    "megaForme": "Venusaur-Mega",
    "megaStone": "Venusaurite",
    "types": [
      "grass",
      "poison"
    ],
    "abilities": {
      "regular": [
        "Thick Fat"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 100,
      "def": 123,
      "spa": 122,
      "spd": 120,
      "spe": 80
    },
    "spritePath": "/assets/pokemon/003/front.png"
  },
  {
    "baseSpecies": "Charizard",
    "megaForme": "Charizard-Mega-X",
    "megaStone": "Charizardite X",
    "types": [
      "fire",
      "dragon"
    ],
    "abilities": {
      "regular": [
        "Tough Claws"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 78,
      "atk": 130,
      "def": 111,
      "spa": 130,
      "spd": 85,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/006/front.png"
  },
  {
    "baseSpecies": "Charizard",
    "megaForme": "Charizard-Mega-Y",
    "megaStone": "Charizardite X",
    "types": [
      "fire",
      "flying"
    ],
    "abilities": {
      "regular": [
        "Drought"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 78,
      "atk": 104,
      "def": 78,
      "spa": 159,
      "spd": 115,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/006/front.png"
  },
  {
    "baseSpecies": "Blastoise",
    "megaForme": "Blastoise-Mega",
    "megaStone": "Blastoisinite",
    "types": [
      "water"
    ],
    "abilities": {
      "regular": [
        "Mega Launcher"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 79,
      "atk": 103,
      "def": 120,
      "spa": 135,
      "spd": 115,
      "spe": 78
    },
    "spritePath": "/assets/pokemon/009/front.png"
  },
  {
    "baseSpecies": "Beedrill",
    "megaForme": "Beedrill-Mega",
    "megaStone": "Beedrillite",
    "types": [
      "bug",
      "poison"
    ],
    "abilities": {
      "regular": [
        "Adaptability"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 65,
      "atk": 150,
      "def": 40,
      "spa": 15,
      "spd": 80,
      "spe": 145
    },
    "spritePath": "/assets/pokemon/015/front.png"
  },
  {
    "baseSpecies": "Pidgeot",
    "megaForme": "Pidgeot-Mega",
    "megaStone": "Pidgeotite",
    "types": [
      "normal",
      "flying"
    ],
    "abilities": {
      "regular": [
        "No Guard"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 83,
      "atk": 80,
      "def": 80,
      "spa": 135,
      "spd": 80,
      "spe": 121
    },
    "spritePath": "/assets/pokemon/018/front.png"
  },
  {
    "baseSpecies": "Alakazam",
    "megaForme": "Alakazam-Mega",
    "megaStone": "Alakazite",
    "types": [
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Trace"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 55,
      "atk": 50,
      "def": 65,
      "spa": 175,
      "spd": 105,
      "spe": 150
    },
    "spritePath": "/assets/pokemon/065/front.png"
  },
  {
    "baseSpecies": "Slowbro",
    "megaForme": "Slowbro-Mega",
    "megaStone": "Slowbronite",
    "types": [
      "water",
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Shell Armor"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 95,
      "atk": 75,
      "def": 180,
      "spa": 130,
      "spd": 80,
      "spe": 30
    },
    "spritePath": "/assets/pokemon/080/front.png"
  },
  {
    "baseSpecies": "Gengar",
    "megaForme": "Gengar-Mega",
    "megaStone": "Gengarite",
    "types": [
      "ghost",
      "poison"
    ],
    "abilities": {
      "regular": [
        "Shadow Tag"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 60,
      "atk": 65,
      "def": 80,
      "spa": 170,
      "spd": 95,
      "spe": 130
    },
    "spritePath": "/assets/pokemon/094/front.png"
  },
  {
    "baseSpecies": "Kangaskhan",
    "megaForme": "Kangaskhan-Mega",
    "megaStone": "Kangaskhanite",
    "types": [
      "normal"
    ],
    "abilities": {
      "regular": [
        "Parental Bond"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 105,
      "atk": 125,
      "def": 100,
      "spa": 60,
      "spd": 100,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/115/front.png"
  },
  {
    "baseSpecies": "Pinsir",
    "megaForme": "Pinsir-Mega",
    "megaStone": "Pinsirite",
    "types": [
      "bug",
      "flying"
    ],
    "abilities": {
      "regular": [
        "Aerilate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 65,
      "atk": 155,
      "def": 120,
      "spa": 65,
      "spd": 90,
      "spe": 105
    },
    "spritePath": "/assets/pokemon/127/front.png"
  },
  {
    "baseSpecies": "Gyarados",
    "megaForme": "Gyarados-Mega",
    "megaStone": "Gyaradosite",
    "types": [
      "water",
      "dark"
    ],
    "abilities": {
      "regular": [
        "Mold Breaker"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 95,
      "atk": 155,
      "def": 109,
      "spa": 70,
      "spd": 130,
      "spe": 81
    },
    "spritePath": "/assets/pokemon/130/front.png"
  },
  {
    "baseSpecies": "Aerodactyl",
    "megaForme": "Aerodactyl-Mega",
    "megaStone": "Aerodactylite",
    "types": [
      "rock",
      "flying"
    ],
    "abilities": {
      "regular": [
        "Tough Claws"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 135,
      "def": 85,
      "spa": 70,
      "spd": 95,
      "spe": 150
    },
    "spritePath": "/assets/pokemon/142/front.png"
  },
  {
    "baseSpecies": "Mewtwo",
    "megaForme": "Mewtwo-Mega-X",
    "megaStone": "Mewtwonite X",
    "types": [
      "psychic",
      "fighting"
    ],
    "abilities": {
      "regular": [
        "Steadfast"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 106,
      "atk": 190,
      "def": 100,
      "spa": 154,
      "spd": 100,
      "spe": 130
    },
    "spritePath": "/assets/pokemon/150/front.png"
  },
  {
    "baseSpecies": "Mewtwo",
    "megaForme": "Mewtwo-Mega-Y",
    "megaStone": "Mewtwonite X",
    "types": [
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Insomnia"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 106,
      "atk": 150,
      "def": 70,
      "spa": 194,
      "spd": 120,
      "spe": 140
    },
    "spritePath": "/assets/pokemon/150/front.png"
  },
  {
    "baseSpecies": "Ampharos",
    "megaForme": "Ampharos-Mega",
    "megaStone": "",
    "types": [
      "electric",
      "dragon"
    ],
    "abilities": {
      "regular": [
        "Mold Breaker"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 90,
      "atk": 95,
      "def": 105,
      "spa": 165,
      "spd": 110,
      "spe": 45
    },
    "spritePath": "/assets/pokemon/181/front.png"
  },
  {
    "baseSpecies": "Steelix",
    "megaForme": "Steelix-Mega",
    "megaStone": "Steelixite",
    "types": [
      "steel",
      "ground"
    ],
    "abilities": {
      "regular": [
        "Sand Force"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 75,
      "atk": 125,
      "def": 230,
      "spa": 55,
      "spd": 95,
      "spe": 30
    },
    "spritePath": "/assets/pokemon/208/front.png"
  },
  {
    "baseSpecies": "Scizor",
    "megaForme": "Scizor-Mega",
    "megaStone": "Scizorite",
    "types": [
      "bug",
      "steel"
    ],
    "abilities": {
      "regular": [
        "Technician"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 150,
      "def": 140,
      "spa": 65,
      "spd": 100,
      "spe": 75
    },
    "spritePath": "/assets/pokemon/212/front.png"
  },
  {
    "baseSpecies": "Heracross",
    "megaForme": "Heracross-Mega",
    "megaStone": "Heracronite",
    "types": [
      "bug",
      "fighting"
    ],
    "abilities": {
      "regular": [
        "Skill Link"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 185,
      "def": 115,
      "spa": 40,
      "spd": 105,
      "spe": 75
    },
    "spritePath": "/assets/pokemon/214/front.png"
  },
  {
    "baseSpecies": "Houndoom",
    "megaForme": "Houndoom-Mega",
    "megaStone": "Houndoominite",
    "types": [
      "dark",
      "fire"
    ],
    "abilities": {
      "regular": [
        "Solar Power"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 75,
      "atk": 90,
      "def": 90,
      "spa": 140,
      "spd": 90,
      "spe": 115
    },
    "spritePath": "/assets/pokemon/229/front.png"
  },
  {
    "baseSpecies": "Tyranitar",
    "megaForme": "Tyranitar-Mega",
    "megaStone": "Tyranitarite",
    "types": [
      "rock",
      "dark"
    ],
    "abilities": {
      "regular": [
        "Sand Stream"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 100,
      "atk": 164,
      "def": 150,
      "spa": 95,
      "spd": 120,
      "spe": 71
    },
    "spritePath": "/assets/pokemon/248/front.png"
  },
  {
    "baseSpecies": "Sceptile",
    "megaForme": "Sceptile-Mega",
    "megaStone": "Sceptilite",
    "types": [
      "grass",
      "dragon"
    ],
    "abilities": {
      "regular": [
        "Lightning Rod"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 110,
      "def": 75,
      "spa": 145,
      "spd": 85,
      "spe": 145
    },
    "spritePath": "/assets/pokemon/254/front.png"
  },
  {
    "baseSpecies": "Blaziken",
    "megaForme": "Blaziken-Mega",
    "megaStone": "Blazikenite",
    "types": [
      "fire",
      "fighting"
    ],
    "abilities": {
      "regular": [
        "Speed Boost"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 160,
      "def": 80,
      "spa": 130,
      "spd": 80,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/257/front.png"
  },
  {
    "baseSpecies": "Swampert",
    "megaForme": "Swampert-Mega",
    "megaStone": "Swampertite",
    "types": [
      "water",
      "ground"
    ],
    "abilities": {
      "regular": [
        "Swift Swim"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 100,
      "atk": 150,
      "def": 110,
      "spa": 95,
      "spd": 110,
      "spe": 70
    },
    "spritePath": "/assets/pokemon/260/front.png"
  },
  {
    "baseSpecies": "Gardevoir",
    "megaForme": "Gardevoir-Mega",
    "megaStone": "Gardevoirite",
    "types": [
      "psychic",
      "fairy"
    ],
    "abilities": {
      "regular": [
        "Pixilate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 68,
      "atk": 85,
      "def": 65,
      "spa": 165,
      "spd": 135,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/282/front.png"
  },
  {
    "baseSpecies": "Sableye",
    "megaForme": "Sableye-Mega",
    "megaStone": "Sablenite",
    "types": [
      "dark",
      "ghost"
    ],
    "abilities": {
      "regular": [
        "Magic Bounce"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 50,
      "atk": 85,
      "def": 125,
      "spa": 85,
      "spd": 115,
      "spe": 20
    },
    "spritePath": "/assets/pokemon/302/front.png"
  },
  {
    "baseSpecies": "Mawile",
    "megaForme": "Mawile-Mega",
    "megaStone": "Mawilite",
    "types": [
      "steel",
      "fairy"
    ],
    "abilities": {
      "regular": [
        "Huge Power"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 50,
      "atk": 105,
      "def": 125,
      "spa": 55,
      "spd": 95,
      "spe": 50
    },
    "spritePath": "/assets/pokemon/303/front.png"
  },
  {
    "baseSpecies": "Aggron",
    "megaForme": "Aggron-Mega",
    "megaStone": "Aggronite",
    "types": [
      "steel"
    ],
    "abilities": {
      "regular": [
        "Filter"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 140,
      "def": 230,
      "spa": 60,
      "spd": 80,
      "spe": 50
    },
    "spritePath": "/assets/pokemon/306/front.png"
  },
  {
    "baseSpecies": "Medicham",
    "megaForme": "Medicham-Mega",
    "megaStone": "Medichamite",
    "types": [
      "fighting",
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Pure Power"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 60,
      "atk": 100,
      "def": 85,
      "spa": 80,
      "spd": 85,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/308/front.png"
  },
  {
    "baseSpecies": "Manectric",
    "megaForme": "Manectric-Mega",
    "megaStone": "Manectricite",
    "types": [
      "electric"
    ],
    "abilities": {
      "regular": [
        "Intimidate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 75,
      "def": 80,
      "spa": 135,
      "spd": 80,
      "spe": 135
    },
    "spritePath": "/assets/pokemon/310/front.png"
  },
  {
    "baseSpecies": "Sharpedo",
    "megaForme": "Sharpedo-Mega",
    "megaStone": "Sharpedonite",
    "types": [
      "water",
      "dark"
    ],
    "abilities": {
      "regular": [
        "Strong Jaw"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 140,
      "def": 70,
      "spa": 110,
      "spd": 65,
      "spe": 105
    },
    "spritePath": "/assets/pokemon/319/front.png"
  },
  {
    "baseSpecies": "Camerupt",
    "megaForme": "Camerupt-Mega",
    "megaStone": "Cameruptite",
    "types": [
      "fire",
      "ground"
    ],
    "abilities": {
      "regular": [
        "Sheer Force"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 120,
      "def": 100,
      "spa": 145,
      "spd": 105,
      "spe": 20
    },
    "spritePath": "/assets/pokemon/323/front.png"
  },
  {
    "baseSpecies": "Altaria",
    "megaForme": "Altaria-Mega",
    "megaStone": "Altarianite",
    "types": [
      "dragon",
      "fairy"
    ],
    "abilities": {
      "regular": [
        "Pixilate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 75,
      "atk": 110,
      "def": 110,
      "spa": 110,
      "spd": 105,
      "spe": 80
    },
    "spritePath": "/assets/pokemon/334/front.png"
  },
  {
    "baseSpecies": "Banette",
    "megaForme": "Banette-Mega",
    "megaStone": "Banettite",
    "types": [
      "ghost"
    ],
    "abilities": {
      "regular": [
        "Prankster"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 64,
      "atk": 165,
      "def": 75,
      "spa": 93,
      "spd": 83,
      "spe": 75
    },
    "spritePath": "/assets/pokemon/354/front.png"
  },
  {
    "baseSpecies": "Absol",
    "megaForme": "Absol-Mega",
    "megaStone": "Absolite",
    "types": [
      "dark"
    ],
    "abilities": {
      "regular": [
        "Magic Bounce"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 65,
      "atk": 150,
      "def": 60,
      "spa": 115,
      "spd": 60,
      "spe": 115
    },
    "spritePath": "/assets/pokemon/359/front.png"
  },
  {
    "baseSpecies": "Glalie",
    "megaForme": "Glalie-Mega",
    "megaStone": "",
    "types": [
      "ice"
    ],
    "abilities": {
      "regular": [
        "Refrigerate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 120,
      "def": 80,
      "spa": 120,
      "spd": 80,
      "spe": 100
    },
    "spritePath": "/assets/pokemon/362/front.png"
  },
  {
    "baseSpecies": "Salamence",
    "megaForme": "Salamence-Mega",
    "megaStone": "",
    "types": [
      "dragon",
      "flying"
    ],
    "abilities": {
      "regular": [
        "Aerilate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 95,
      "atk": 145,
      "def": 130,
      "spa": 120,
      "spd": 90,
      "spe": 120
    },
    "spritePath": "/assets/pokemon/373/front.png"
  },
  {
    "baseSpecies": "Metagross",
    "megaForme": "Metagross-Mega",
    "megaStone": "",
    "types": [
      "steel",
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Tough Claws"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 145,
      "def": 150,
      "spa": 105,
      "spd": 110,
      "spe": 110
    },
    "spritePath": "/assets/pokemon/376/front.png"
  },
  {
    "baseSpecies": "Latias",
    "megaForme": "Latias-Mega",
    "megaStone": "Latiasite",
    "types": [
      "dragon",
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Levitate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 100,
      "def": 120,
      "spa": 140,
      "spd": 150,
      "spe": 110
    },
    "spritePath": "/assets/pokemon/380/front.png"
  },
  {
    "baseSpecies": "Latios",
    "megaForme": "Latios-Mega",
    "megaStone": "Latiosite",
    "types": [
      "dragon",
      "psychic"
    ],
    "abilities": {
      "regular": [
        "Levitate"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 80,
      "atk": 130,
      "def": 100,
      "spa": 160,
      "spd": 120,
      "spe": 110
    },
    "spritePath": "/assets/pokemon/381/front.png"
  },
  {
    "baseSpecies": "Rayquaza",
    "megaForme": "Rayquaza-Mega",
    "megaStone": "Rayquazite",
    "types": [
      "dragon",
      "flying"
    ],
    "abilities": {
      "regular": [
        "Delta Stream"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 105,
      "atk": 180,
      "def": 100,
      "spa": 180,
      "spd": 100,
      "spe": 115
    },
    "spritePath": "/assets/pokemon/384/front.png"
  },
  {
    "baseSpecies": "Lopunny",
    "megaForme": "Lopunny-Mega",
    "megaStone": "Lopunnite",
    "types": [
      "normal",
      "fighting"
    ],
    "abilities": {
      "regular": [
        "Scrappy"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 65,
      "atk": 136,
      "def": 94,
      "spa": 54,
      "spd": 96,
      "spe": 135
    },
    "spritePath": "/assets/pokemon/428/front.png"
  },
  {
    "baseSpecies": "Garchomp",
    "megaForme": "Garchomp-Mega",
    "megaStone": "Garchompite",
    "types": [
      "dragon",
      "ground"
    ],
    "abilities": {
      "regular": [
        "Sand Force"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 108,
      "atk": 170,
      "def": 115,
      "spa": 120,
      "spd": 95,
      "spe": 92
    },
    "spritePath": "/assets/pokemon/445/front.png"
  },
  {
    "baseSpecies": "Lucario",
    "megaForme": "Lucario-Mega",
    "megaStone": "Lucarionite",
    "types": [
      "fighting",
      "steel"
    ],
    "abilities": {
      "regular": [
        "Adaptability"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 70,
      "atk": 145,
      "def": 88,
      "spa": 140,
      "spd": 70,
      "spe": 112
    },
    "spritePath": "/assets/pokemon/448/front.png"
  },
  {
    "baseSpecies": "Abomasnow",
    "megaForme": "Abomasnow-Mega",
    "megaStone": "",
    "types": [
      "grass",
      "ice"
    ],
    "abilities": {
      "regular": [
        "Snow Warning"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 90,
      "atk": 132,
      "def": 105,
      "spa": 132,
      "spd": 105,
      "spe": 30
    },
    "spritePath": "/assets/pokemon/460/front.png"
  },
  {
    "baseSpecies": "Gallade",
    "megaForme": "Gallade-Mega",
    "megaStone": "",
    "types": [
      "psychic",
      "fighting"
    ],
    "abilities": {
      "regular": [
        "Inner Focus"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 68,
      "atk": 165,
      "def": 95,
      "spa": 65,
      "spd": 115,
      "spe": 110
    },
    "spritePath": "/assets/pokemon/475/front.png"
  },
  {
    "baseSpecies": "Audino",
    "megaForme": "Audino-Mega",
    "megaStone": "Audinite",
    "types": [
      "normal",
      "fairy"
    ],
    "abilities": {
      "regular": [
        "Healer"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 103,
      "atk": 60,
      "def": 126,
      "spa": 80,
      "spd": 126,
      "spe": 50
    },
    "spritePath": "/assets/pokemon/531/front.png"
  },
  {
    "baseSpecies": "Diancie",
    "megaForme": "Diancie-Mega",
    "megaStone": "Diancite",
    "types": [
      "rock",
      "fairy"
    ],
    "abilities": {
      "regular": [
        "Magic Bounce"
      ],
      "hidden": []
    },
    "baseStats": {
      "hp": 50,
      "atk": 160,
      "def": 110,
      "spa": 160,
      "spd": 110,
      "spe": 110
    },
    "spritePath": "/assets/pokemon/719/front.png"
  }
];

const MEGA_BY_STONE = new Map<string, MegaEvolutionData>();
const MEGA_BY_BASE = new Map<string, MegaEvolutionData[]>();

for (const m of MEGA_EVOLUTIONS) {
  if (m.megaStone) MEGA_BY_STONE.set(m.megaStone.toLowerCase(), m);
  const key = m.baseSpecies.toLowerCase();
  if (!MEGA_BY_BASE.has(key)) MEGA_BY_BASE.set(key, []);
  MEGA_BY_BASE.get(key)!.push(m);
}

export function getMegaByStone(stoneName: string): MegaEvolutionData | undefined {
  return MEGA_BY_STONE.get(stoneName.toLowerCase());
}

export function getMegasForSpecies(species: string): MegaEvolutionData[] {
  return MEGA_BY_BASE.get(species.toLowerCase()) || [];
}

export function getAllMegaEvolutions(): MegaEvolutionData[] {
  return MEGA_EVOLUTIONS;
}
