// AUTO-GENERATED by scripts/poke-data-sync.mjs — DO NOT EDIT
import type { TypeEffectiveness, PokemonType } from '../../data/pokemon/schemas/index.ts';

export const TYPES: TypeEffectiveness[] = [
  {
    "name": "bug",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 2,
      "fire": 1,
      "flying": 1,
      "ghost": 0,
      "grass": 2,
      "ground": 2,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 1,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "dark",
    "damageTaken": {
      "bug": 1,
      "dark": 2,
      "dragon": 0,
      "electric": 0,
      "fairy": 1,
      "fighting": 1,
      "fire": 0,
      "flying": 0,
      "ghost": 2,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 3,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "dragon",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 1,
      "electric": 2,
      "fairy": 1,
      "fighting": 0,
      "fire": 2,
      "flying": 0,
      "ghost": 0,
      "grass": 2,
      "ground": 0,
      "ice": 1,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 0,
      "steel": 0,
      "water": 2
    }
  },
  {
    "name": "electric",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 2,
      "fairy": 0,
      "fighting": 0,
      "fire": 0,
      "flying": 2,
      "ghost": 0,
      "grass": 0,
      "ground": 1,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 0,
      "steel": 2,
      "water": 0
    }
  },
  {
    "name": "fairy",
    "damageTaken": {
      "bug": 2,
      "dark": 2,
      "dragon": 3,
      "electric": 0,
      "fairy": 0,
      "fighting": 2,
      "fire": 0,
      "flying": 0,
      "ghost": 0,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 1,
      "psychic": 0,
      "rock": 0,
      "steel": 1,
      "water": 0
    }
  },
  {
    "name": "fighting",
    "damageTaken": {
      "bug": 2,
      "dark": 2,
      "dragon": 0,
      "electric": 0,
      "fairy": 1,
      "fighting": 0,
      "fire": 0,
      "flying": 1,
      "ghost": 0,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 1,
      "rock": 2,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "fire",
    "damageTaken": {
      "bug": 2,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 2,
      "fighting": 0,
      "fire": 2,
      "flying": 0,
      "ghost": 0,
      "grass": 2,
      "ground": 1,
      "ice": 2,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 1,
      "steel": 2,
      "water": 1
    }
  },
  {
    "name": "flying",
    "damageTaken": {
      "bug": 2,
      "dark": 0,
      "dragon": 0,
      "electric": 1,
      "fairy": 0,
      "fighting": 2,
      "fire": 0,
      "flying": 0,
      "ghost": 0,
      "grass": 2,
      "ground": 3,
      "ice": 1,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 1,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "ghost",
    "damageTaken": {
      "bug": 2,
      "dark": 1,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 3,
      "fire": 0,
      "flying": 0,
      "ghost": 1,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 3,
      "poison": 2,
      "psychic": 0,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "grass",
    "damageTaken": {
      "bug": 1,
      "dark": 0,
      "dragon": 0,
      "electric": 2,
      "fairy": 0,
      "fighting": 0,
      "fire": 1,
      "flying": 1,
      "ghost": 0,
      "grass": 2,
      "ground": 2,
      "ice": 1,
      "normal": 0,
      "poison": 1,
      "psychic": 0,
      "rock": 0,
      "steel": 0,
      "water": 2
    }
  },
  {
    "name": "ground",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 3,
      "fairy": 0,
      "fighting": 0,
      "fire": 0,
      "flying": 0,
      "ghost": 0,
      "grass": 1,
      "ground": 0,
      "ice": 1,
      "normal": 0,
      "poison": 2,
      "psychic": 0,
      "rock": 2,
      "steel": 0,
      "water": 1
    }
  },
  {
    "name": "ice",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 1,
      "fire": 1,
      "flying": 0,
      "ghost": 0,
      "grass": 0,
      "ground": 0,
      "ice": 2,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 1,
      "steel": 1,
      "water": 0
    }
  },
  {
    "name": "normal",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 1,
      "fire": 0,
      "flying": 0,
      "ghost": 3,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "poison",
    "damageTaken": {
      "bug": 2,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 2,
      "fighting": 2,
      "fire": 0,
      "flying": 0,
      "ghost": 0,
      "grass": 2,
      "ground": 1,
      "ice": 0,
      "normal": 0,
      "poison": 2,
      "psychic": 1,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "psychic",
    "damageTaken": {
      "bug": 1,
      "dark": 1,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 2,
      "fire": 0,
      "flying": 0,
      "ghost": 1,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 2,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "rock",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 1,
      "fire": 2,
      "flying": 2,
      "ghost": 0,
      "grass": 1,
      "ground": 1,
      "ice": 0,
      "normal": 2,
      "poison": 2,
      "psychic": 0,
      "rock": 0,
      "steel": 1,
      "water": 1
    }
  },
  {
    "name": "steel",
    "damageTaken": {
      "bug": 2,
      "dark": 0,
      "dragon": 2,
      "electric": 0,
      "fairy": 2,
      "fighting": 1,
      "fire": 1,
      "flying": 2,
      "ghost": 0,
      "grass": 2,
      "ground": 1,
      "ice": 2,
      "normal": 2,
      "poison": 3,
      "psychic": 2,
      "rock": 2,
      "steel": 2,
      "water": 0
    }
  },
  {
    "name": "stellar",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 0,
      "fairy": 0,
      "fighting": 0,
      "fire": 0,
      "flying": 0,
      "ghost": 0,
      "grass": 0,
      "ground": 0,
      "ice": 0,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 0,
      "steel": 0,
      "water": 0
    }
  },
  {
    "name": "water",
    "damageTaken": {
      "bug": 0,
      "dark": 0,
      "dragon": 0,
      "electric": 1,
      "fairy": 0,
      "fighting": 0,
      "fire": 2,
      "flying": 0,
      "ghost": 0,
      "grass": 1,
      "ground": 0,
      "ice": 2,
      "normal": 0,
      "poison": 0,
      "psychic": 0,
      "rock": 0,
      "steel": 2,
      "water": 2
    }
  }
];

export const TYPE_NAMES: PokemonType[] = TYPES.map(t => t.name);

export function getTypeByName(name: string): TypeEffectiveness | undefined {
  return TYPES.find(t => t.name === name.toLowerCase());
}

export function getTypeById(id: number): TypeEffectiveness | undefined {
  return TYPES.find(t => t.id === id);
}

export function getEffectiveness(attackType: string, defenseTypes: string[]): number {
  let multiplier = 1;
  const atkType = attackType.toLowerCase();
  const typeData = getTypeByName(atkType);
  if (!typeData) return multiplier;
  
  for (const defType of defenseTypes) {
    const value = typeData.damageTaken[defType.toLowerCase() as PokemonType];
    if (value === 2) multiplier *= 2;
    else if (value === 1) multiplier *= 0.5;
    else if (value === 3 || value === 4) multiplier *= 0;
  }
  
  return multiplier;
}
