/**
 * Hand-authored per-move overrides.
 *
 * This is the ONLY place per-move animation authoring happens, and it stays small on
 * purpose: profileResolver derives a sensible category for every move in the dataset
 * from its flags/category/power, so this table is reserved for signature moves whose
 * silhouette should differ from the derived default.
 *
 * Adding a bespoke animation later is one row here. No engine change, no new component.
 */

import type { ProfileOverride } from './animationTypes';

export const MOVE_PROFILE_OVERRIDES: Record<string, ProfileOverride> = {
  // ── Beams: sustained, charged, held through contact ──
  flamethrower: { category: 'BEAM' },
  fireblast: { category: 'BEAM', modifiers: ['heavy'] },
  overheat: { category: 'BEAM', modifiers: ['heavy'] },
  hydropump: { category: 'BEAM', modifiers: ['heavy'] },
  hydrocannon: { category: 'BEAM', modifiers: ['heavy'] },
  icebeam: { category: 'BEAM', knobs: { decal: 'shockring' } },
  thunderbolt: { category: 'BEAM', timings: { travelMs: 120 }, knobs: { arcHeight: 0 } },
  thunder: { category: 'BEAM', modifiers: ['heavy'], timings: { travelMs: 110 } },
  solarbeam: { category: 'BEAM', modifiers: ['heavy'], timings: { windupMs: 420 } },
  hyperbeam: { category: 'BEAM', modifiers: ['heavy'], timings: { windupMs: 380, impactMs: 140 } },
  aurasphere: { category: 'PROJECTILE', knobs: { arcHeight: 0.05 } },
  dragonpulse: { category: 'BEAM' },
  darkpulse: { category: 'BEAM' },
  flashcannon: { category: 'BEAM' },
  earthpower: { category: 'AREA_GROUND', knobs: { decal: 'crack' } },
  focusblast: { category: 'PROJECTILE', modifiers: ['heavy'] },
  psybeam: { category: 'BEAM' },
  chargebeam: { category: 'BEAM', timings: { travelMs: 120 } },
  bubblebeam: { category: 'PROJECTILE', knobs: { arcHeight: 0.45 } },
  aurorabeam: { category: 'BEAM' },
  mirrorshot: { category: 'BEAM' },

  // ── Ground / area: force from the floor ──
  earthquake: { category: 'AREA_GROUND', modifiers: ['heavy'] },
  bulldoze: { category: 'AREA_GROUND', knobs: { shockwaveRadius: 2.4 } },
  magnitude: { category: 'AREA_GROUND' },
  fissure: { category: 'AREA_GROUND', modifiers: ['heavy'] },
  rockslide: { category: 'AREA_GROUND', knobs: { decal: 'crack', arcHeight: 0.6 } },
  stoneedge: { category: 'AREA_GROUND', modifiers: ['heavy'], knobs: { decal: 'crack' } },
  rocktomb: { category: 'AREA_GROUND', knobs: { shockwaveRadius: 2.1 } },
  eruption: { category: 'AREA_GROUND', modifiers: ['heavy'] },
  dig: { category: 'AREA_GROUND' },

  // ── Sweeping walls ──
  surf: { category: 'AREA_WAVE' },
  sludgewave: { category: 'AREA_WAVE' },
  heatwave: { category: 'AREA_WAVE' },
  hurricane: { category: 'AREA_WAVE' },
  blizzard: { category: 'AREA_WAVE', modifiers: ['heavy'] },
  discharge: { category: 'AREA_WAVE', timings: { travelMs: 140 } },
  bugbuzz: { category: 'AREA_WAVE' },
  boomburst: { category: 'AREA_WAVE', modifiers: ['heavy'] },
  muddywater: { category: 'AREA_WAVE' },
  icywind: { category: 'AREA_WAVE' },
  snarl: { category: 'AREA_WAVE' },
  strugglebug: { category: 'AREA_WAVE' },
  aircutter: { category: 'AREA_WAVE' },
  silverwind: { category: 'AREA_WAVE' },
  hypervoice: { category: 'AREA_WAVE' },
  dazzlinggleam: { category: 'AREA_WAVE' },
  swift: { category: 'PROJECTILE', knobs: { arcHeight: 0.5, projectile: 'shard' } },

  // ── Slashes: dash through with a crescent ──
  slash: { category: 'SLASH' },
  cut: { category: 'SLASH' },
  leafblade: { category: 'SLASH' },
  airslash: { category: 'SLASH', knobs: { dashThrough: false, lunge: 0.3 } },
  xscissor: { category: 'SLASH' },
  crosschop: { category: 'SLASH' },
  nightslash: { category: 'SLASH' },
  psychocut: { category: 'SLASH', knobs: { dashThrough: false, lunge: 0.25 } },
  shadowclaw: { category: 'SLASH' },
  dragonclaw: { category: 'SLASH' },
  metalclaw: { category: 'SLASH' },
  furycutter: { category: 'SLASH' },
  razorleaf: { category: 'PROJECTILE', knobs: { projectile: 'shard', arcHeight: 0.3 } },
  aerialace: { category: 'SLASH', knobs: { lunge: 1.1 } },
  sacredsword: { category: 'SLASH', modifiers: ['heavy'] },

  // ── Heavy contact ──
  closecombat: { category: 'MULTI_HIT', modifiers: ['heavy'], knobs: { heroScale: 1.15 } },
  flareblitz: { category: 'CONTACT_STRIKE', modifiers: ['heavy', 'recoil'], knobs: { decal: 'burst' } },
  bravebird: { category: 'CONTACT_STRIKE', modifiers: ['heavy', 'recoil'], knobs: { lunge: 1.05 } },
  doubleedge: { category: 'CONTACT_STRIKE', modifiers: ['heavy', 'recoil'] },
  wildcharge: { category: 'CONTACT_STRIKE', modifiers: ['heavy', 'recoil'] },
  volttackle: { category: 'CONTACT_STRIKE', modifiers: ['heavy', 'recoil'] },
  ironhead: { category: 'CONTACT_STRIKE', modifiers: ['heavy'] },
  megahorn: { category: 'CONTACT_STRIKE', modifiers: ['heavy'] },
  playrough: { category: 'MULTI_HIT' },
  outrage: { category: 'MULTI_HIT', modifiers: ['heavy'] },
  liquidation: { category: 'CONTACT_STRIKE' },
  icicle: { category: 'PROJECTILE', knobs: { projectile: 'shard' } },
  iciclecrash: { category: 'AREA_GROUND', knobs: { decal: 'crack' } },
  phantomforce: { category: 'CONTACT_STRIKE', modifiers: ['heavy'] },
  gigaimpact: { category: 'CONTACT_STRIKE', modifiers: ['heavy'], knobs: { lunge: 1.15 } },

  // ── Priority jabs: the stance breakers ──
  quickattack: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  machpunch: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  bulletpunch: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  aquajet: { category: 'CONTACT_STRIKE', modifiers: ['quick'], knobs: { lunge: 0.85 } },
  iceshard: { category: 'PROJECTILE', modifiers: ['quick'], knobs: { projectile: 'shard', arcHeight: 0.1 } },
  shadowsneak: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  suckerpunch: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  vacuumwave: { category: 'PROJECTILE', modifiers: ['quick'] },
  flamecharge: { category: 'CONTACT_STRIKE', modifiers: ['quick'], knobs: { lunge: 0.9 } },
  accelerock: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  fakeout: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  nuzzle: { category: 'CONTACT_STRIKE', modifiers: ['quick'] },
  dragontail: { category: 'CONTACT_STRIKE' },

  // ── Projectiles ──
  shadowball: { category: 'PROJECTILE', knobs: { arcHeight: 0.28 } },
  moonblast: { category: 'PROJECTILE', modifiers: ['heavy'] },
  sludgebomb: { category: 'PROJECTILE', knobs: { arcHeight: 0.6, decal: 'burst' } },
  energyball: { category: 'PROJECTILE', knobs: { arcHeight: 0.3 } },
  gunkshot: { category: 'PROJECTILE', modifiers: ['heavy'], knobs: { arcHeight: 0.5 } },
  seedbomb: { category: 'PROJECTILE', knobs: { arcHeight: 0.7 } },
  powergem: { category: 'PROJECTILE', knobs: { projectile: 'shard' } },
  ancientpower: { category: 'PROJECTILE', knobs: { projectile: 'shard', arcHeight: 0.4 } },
  rockthrow: { category: 'PROJECTILE', knobs: { projectile: 'shard', arcHeight: 0.55 } },
  mudshot: { category: 'PROJECTILE', knobs: { arcHeight: 0.5 } },
  mudslap: { category: 'PROJECTILE', knobs: { arcHeight: 0.35 } },
  dracometeor: { category: 'AREA_GROUND', modifiers: ['heavy'], knobs: { arcHeight: 1.2, decal: 'burst' } },
  drainingkiss: { category: 'PROJECTILE', knobs: { heroSheet: 'sparkle' } },
  fairywind: { category: 'PROJECTILE', knobs: { arcHeight: 0.2 } },
  gigadrain: { category: 'BEAM', knobs: { heroSheet: 'sparkle' } },
  megadrain: { category: 'BEAM' },
  absorb: { category: 'BEAM' },
  hex: { category: 'PROJECTILE' },
  astonish: { category: 'PROJECTILE', modifiers: ['quick'] },
  confusion: { category: 'PROJECTILE', knobs: { arcHeight: 0.1 } },
  psyshock: { category: 'PROJECTILE' },
  psychic: { category: 'AREA_WAVE', modifiers: ['heavy'] },
  gust: { category: 'PROJECTILE', knobs: { arcHeight: 0.15 } },

  // ── Status delivery ──
  thunderwave: { category: 'STATUS_APPLY' },
  willowisp: { category: 'STATUS_APPLY' },
  toxic: { category: 'STATUS_APPLY' },
  poisonpowder: { category: 'STATUS_APPLY' },
  sleeppowder: { category: 'STATUS_APPLY' },
  spore: { category: 'STATUS_APPLY' },
  stunspore: { category: 'STATUS_APPLY' },
  hypnosis: { category: 'STATUS_APPLY' },
  confuseray: { category: 'STATUS_APPLY' },
  leechseed: { category: 'STATUS_APPLY' },
  growl: { category: 'STATUS_APPLY' },
  leer: { category: 'STATUS_APPLY' },
  tailwhip: { category: 'STATUS_APPLY' },
  screech: { category: 'STATUS_APPLY' },
  metalsound: { category: 'STATUS_APPLY' },
  sandattack: { category: 'STATUS_APPLY' },
  charm: { category: 'STATUS_APPLY' },
  stringshot: { category: 'STATUS_APPLY' },
  torment: { category: 'STATUS_APPLY' },
  lowsweep: { category: 'CONTACT_STRIKE' },
  mist: { category: 'SELF_BUFF' },

  // ── Setup ──
  swordsdance: { category: 'SELF_BUFF' },
  nastyplot: { category: 'SELF_BUFF' },
  calmmind: { category: 'SELF_BUFF' },
  bulkup: { category: 'SELF_BUFF' },
  dragondance: { category: 'SELF_BUFF' },
  irondefense: { category: 'SELF_BUFF' },
  acidarmor: { category: 'SELF_BUFF' },
  agility: { category: 'SELF_BUFF' },
  rockpolish: { category: 'SELF_BUFF' },
  workup: { category: 'SELF_BUFF' },
  growth: { category: 'SELF_BUFF' },
  harden: { category: 'SELF_BUFF' },
  amnesia: { category: 'SELF_BUFF' },

  // ── Recovery ──
  recover: { category: 'HEAL' },
  softboiled: { category: 'HEAL' },
  roost: { category: 'HEAL' },
  moonlight: { category: 'HEAL' },
  synthesis: { category: 'HEAL' },
  morningsun: { category: 'HEAL' },
  slackoff: { category: 'HEAL' },
  rest: { category: 'HEAL' },
  milkdrink: { category: 'HEAL' },
};
